### ISSUE TITLE
[Feature Request] dump logs in case of smoke test failure

### ISSUE THREAD

**Issue by zekun000** [libra/libra#1049]
Smoke test is hard to debug without logs, and we're not able to grab the libra node logs from CI.

Currently it requires we re-run the test and ssh into the hosts, but it doesn't help with flaky hard-to-reproduce tests.

Feature requested - When the swarm detect the process failure, it could dump the logs to test console so that we can get more visibility.

**Comment by bmwill** [comment]
I've got an idea for how to fix this, but basically all of the logs for each validator are going to get dumped to the console. So while you'll have the logs it still might be difficult to look at them. I think that maybe putting in a delimiter between logs from different validators will make it easier to see when one validator's logs being and another ends.

**Comment by zekun000** [comment]
@bmwill can we only dump the log from failed nodes i.e. only re-direct from the `LibraNode::Drop` when it crashes?

**Comment by andll** [comment]
We could keep same logic as it was before with LogTee - dump log entries to stdout of test thread, interleaving logs from different validators and prefixing them with `[NodeId]`.
In this case rust test runner will take care of only printing this log if test fails

Previously we were using set_stdio for this, since its not available we could just use channel to send output to main thread

**Comment by bmwill** [comment]
@zekun000 yes logs will only be dumped on failure.
