### ISSUE TITLE
[Roadmap] TCB (Trusted Computing Base)

### ISSUE THREAD

**Issue by ericnakagawa** [libra/libra#1142]

**Comment by davidiw** [comment]
# Libra Core TCB
This issue encompasses a broad plan to build a TCB that ensures correctness of the Libra blockchain. Specifically, the TCB's goal is to ensure that any consensus vote signed by validators correctly extends the blockchain. In turn, any client query will return a signed ledger info that verifies the correctness of the response and that state is irreversible (outside of FTVMs). Finally, any correct replay of all transactions within the blockchain should result in the same state signed by validators in ledger info.

## Motivations

1. Isolate critical properties within a finite space
2. Make it easier to identify how a property was violated
3. Improve the ability to audit for these properties
4. Establish paradigms for code isolation / separation as early in the build cycle as possible
5. Establish secure deployment principles early

## Properties (P)
1. Maintain a linear consensus history (Never vote on something that would cause a consensus fork)
2. Maintain an append-only ledger history (Never vote on something that would cause a storage fork)
3. Untrusted storage - Maintain integrity of storage (Never vote on bad execution state)
4. Correct execution - All agreed upon transactions within a block execute in order and correctly (Always execute transactions correctly)

## High-level Overview (HLO)
1. Separation and isolation of consensus safety rules from the rest of consensus to ensure that a compromised validator cannot vote on a fork to consensus without compromising this module. A fork exists when two ledgers or committed blocks, LI1 and LI2, do not have a linear relationship, in other words, neither LI1 is a prefix of LI2 nor LI2 is a prefix of LI1.
2. Separation of the VM/Executor with an integrity providing interface into storage. More specifically, that during reads by the VM/Executor verifies the state of storage matches that of the preceding write. Note: speculative state is stored only in memory and within the trust boundary of the VM/Executor.
3. Secure path between VM/Executor and Consensus Safety Rules to ensure that only correct state is voted upon.

## Mapping High-Level Overviews to Properties
* HLO1 provides P1 and P2. Specifically, this is the SafetyRules TCB.
* HLO2 provides P3. This assumes that there is a trusted means to provide transactions and the proper execution state to the VM/Executor, which in turn can ensure it is executing only on verified state.
* HLO3 provides P4. Takes the responsibility of verifying that block integrity is maintained, that is, it is the trusted means to provide transactions and proper execution state to the VM/Executor.

## Naming
* Proposal or Block - A list of transactions and a pointer to the previous block
* LSR - Libra Safety Rules TCB for Consensus Safety
* LEC - Libra Execution Correctness TCB for the Exec/VM
* TCB - Trusted Computing Base incorporating LSR, LEC, and the communication pathway between the two.
* Waypoint - A trusted data structure that enables a node to bootstrap trust at a specific time without having to replay state from genesis

## Assumptions
* LSR only certifies that consensus has no forks and does not enforce the correctness of the underlying system (execution)
* LEC assumes that it has received a correctly formed proposal from LSR
* LSR assumes that the output from LEC is correct but verifies that it appends the input state.

## Proposed Process
![tcb](https://user-images.githubusercontent.com/73818/73221066-cfd1b580-4114-11ea-8165-eee389033c87.png)

### Setup
* LSR knows the last voted round, the largest head of a two chain of rounds, and a valid Waypoint. 
* The Waypoint verifies the correctness of a LedgerInfo containing the set of Validators (including their public keys) and epoch. LSR is the only holder of the consensus private key.
* LSR has access to a secrets manager that stores data persistently and reads from that at startup to retrieve the above information.
* LEC maintains a cache of executed state.

### Trust
* Trust zone -1 hold the association member’s account authorization key, the association member’s account blesses a validator account to handle online key rotation
* Trust zone 0 has access to all keys including the validator account’s authorization key so that it can rotate the consensus key
* Trust zone 1 has access to the consensus key and ensures that forking cannot occur
* Trust zone 2 takes responsibility for verifying the integrity of storage and faithfully executing transactions
* Trust zone 3 is the last trusted of the trust zones and acts as the bridge between untrusted and trusted

### Normal execution
* Consensus receives a proposal and quorum certificate (QC) for parent proposal
* Consensus stores the proposal to disk
* (1) Consensus passes the proposal to LSR
* LSR verifies the correctness of the proposal
  * The epoch in the proposal is the current epoch
  * The last voted round is less than the proposed round
  * The proposed rounds parent is greater than or equal to the highest two-head chain
  * The proposal and the proposal’s QC are correctly signed
* (2) LSR asks LEC to execute the transactions using the parent’s root state hash provided in the QuorumCertificate within the proposal
* LEC obtains a verified read into storage and the scratchpad leveraging the last committed state and the speculative state as defined by the root state hash
* LEC executes each transaction
  * Retrieve authentication key for account performs transaction
  * (3) Verify correctness of this read via accumulator hash
  * Performs transaction
  * Verifies each read during the transaction
  * Stores each write to a transaction write set
* LEC computes a new speculative state starting with the input speculative state and appending the transaction write set
* (4) LEC stores execution to the scratch pad
* (5) LEC transmits the output sparse merkle tree and potentially an updated validator set to LSR
LSR performs pre-vote checks votes
  * If validator set is present, verifies that its public key is in the set
  * Compute the new state output and ensure it extends the parent
  * Update to the next epoch / validator set if this commit would trigger an epoch change / validator set change
* LSR updates itself and persistent storage with the new update to last vote round and potential update to largest head of a two chain of rounds. If this is an epoch change, LSR also updates the Waypoint.
* LSR constructs and signs a vote message certifying the proposal
* (6) LSR transmits the vote to consensus

### Timeout
* Consensus waits until a timeout occurs
* Asks LSR for a signed timeout message for a specific round and epoch
* LSR checks that the round > than the last vote round and the epoch is current
* LSR updates persistent storage with the last vote round
* LSR sends back a signature for the timeout message

### Proposal generation
* Consensus generates a proposal containing a set of transactions, selects the appropriate parent QC, and submits it to LSR
* LSR verifies correctness of the proposal
  * Round > last vote round
  * Epoch is current
  * The certified round in the QC is greater than or equal to the highest two-head chain
  * The signature on the QC

### Restarting
* Consensus acquires all uncommitted blocks from persistent store
* (1) Consensus asks SafetyRules to replay the transactions
* SafetyRules verifies
  * The epoch in the proposals match the current epoch
  * Proposals to be replayed match a preferred_round check
  * The proposal and the proposal’s QC are correctly signed
* SafetyRules passes each block at a time to execution
* (2) LSR asks LEC to execute the transactions using the parent’s root state hash provided in the QuorumCertificate within the proposal
* LEC obtains a verified read into storage and the scratchpad leveraging the last committed state and the speculative state as defined by the root state hash
* LEC executes each transaction
  * Retrieve authentication key for account performs transaction
  * (3) Verify correctness of this read via accumulator hash
  * Performs transaction
  * Verifies each read during the transaction
  * Stores each write to a transaction write set
* LEC computes a new speculative state starting with the input speculative state and appending the transaction write set
* (4) LEC stores execution to the scratch pad
* (5) LEC transmits the output sparse merkle tree and potentially an updated validator set to LSR

### Starting
* SafetyRules parses from disk a hash of a ledger info (waypoint)
* Consensus queries SafetyRules for last known good state
* SafetyRules responds with the ledger info
* If this matches current state continue with restarting
* Else Consensus acquires appropriate QCs to update SafetyRules to the current state -- this is only strictly required if there had been epoch changes

### Exiting epoch
* SafetyRules receives a NIL block that commits an epoch change
* SafetyRules performs
  * The normal verifications
  * Resets last_voted_round and preferred_round to 0
  * Increments the epoch
  * Computes a new ledger info (waypoint) and stores that to disk

### Entering epoch (and starting for the first time)
* QC will not be signed but instead will match the entry within the waypoint, the QC round will be 0

## Additional Proposals
* LSR verification of transaction accumulator hash - this is unnecessary in a system where we have a system-wide TCB. It does prevent malicious validators from deleting history but these nodes can still add or mutate transactions with LSR alone, specifically without having LEC. Because of this property, we have included this as a feature in the above process.
* LSR should verify block dependency before voting on a block. Under normal circumstances, LSR receives a QC certifying that the proposal correctly points to its parent and its parent to the block about to be committed. In cases where there has been lost rounds, this commitment may result in additional blocks being committed. There is no need to re-verify that blocks are linear because LEC verifies correctness of transactions on top of the storage specified by the QC. This is not included in the above.
* Enable online key rotation of consensus keys. This makes long range attacks, wherein an attacker slowly acquires keys, difficult as keys may only have a valid lifetime of a day or a week. The module responsible for key rotation would belong to LSR. This is independent of the above.
* Pass executed state output from Consensus to LSR and then to LEC with proof of correctness. This is a delta from the above proposal in that LEC would no longer need a cache or need to be rebuilt. The tradeoff is in terms of bandwidth and computation during the correctness verification versus the code complexity of handling crashes and handling outbound communication from LSR to LEC. We should consider building this to validate performance if it is a concern. A proof of correctness could either be signing the output with a key specific to LEC or leveraging the root hash to ensure that it is correct.
* Pass uncommitted blocks between a proposal and the last committed state to LEC when committing or voting. This is the naive approach to handling the separation of LEC and Consensus.

## Dependencies

* Secrets Manager (secure, persistent storage) for keys and data
* Key Manager
* Lightweight networking / RPC

**Comment by davidiw** [comment]
Going to open up a new issue.
