### ISSUE TITLE
[Roadmap][Move] Events

### ISSUE THREAD

**Issue by ericnakagawa** [libra/libra#1146]
This issue tracks implementing an event system for the Move VM and a way to emit events from Move code.

**Comment by lucasverra** [comment]
yeah events !

**Comment by bob-wilson** [comment]
The Move event system has been in place since July. In addition to https://github.com/libra/libra/pull/1473 referenced above, we have made some other changes to revise events since that initial implementation. For example, once we had generic types in Move, we changed events to make them generic (https://github.com/libra/libra/pull/940). Most recently, we changed to use transparent addresses for EventKeys (https://github.com/libra/libra/pull/1729). At this point, we are not aware of other changes that are needed for events, and this issue can be closed.
