### ISSUE TITLE
Running main function of a .mvir file from terminal

### ISSUE THREAD

**Issue by Noah-Vincenz** [libra/libra#115]
How can one execute the main function of a .mvir file from the terminal? For example running create_account_script.mvir with address and amount as arguments? I could not find any details  on this in the documentation.

**Comment by sblackshear** [comment]
Good question. This is a bit more complicated than it sounds because the `main` procedure must be executed in the context of a particular global blockchain state. We are working on a testing environment that will let you do this using a dummy global state with a few test accounts. The discourse post [here](https://community.libra.org/t/steps-to-deploy-use-a-custom-module-in-local-testnet/253) has some more details.

**Comment by davidiw** [comment]
Gonna close this out as there's a post in discourse.
