### ISSUE TITLE
Why you guys create a new smart contract language again?

### ISSUE THREAD

**Issue by shannon1916** [libra/libra#12]
Why not use Solidity or WASM?

**Comment by acodercc** [comment]
i like es6 or typescript

**Comment by zengxinhai** [comment]
Yup, I wanna javascript!!!

**Comment by peterfifthrow** [comment]
I'm not involved with this project, but:

* WASM is not a language.
* Solidity is not a language that should be used for applications with real money involved. It is inherently dangerous, and history has shown this in very painful ways.

Smart contracts are still a new research area. The more innovation the better, because it means we can discard the bad ideas (for example Solidity) sooner. WASM may one day be ubiquitous in all kinds of areas, including smart contracts. Safe, formally verifiable languages, suitable for smart contracts might target WASM - or not.

**Comment by peterjoel** [comment]
I'm not involved with this project, but:

* WASM is not a language.
* Solidity is not a language that should be used for applications with real money involved. It is inherently dangerous, and history has shown this in very painful ways.

Smart contracts are still a new research area. The more innovation the better, because it means we can discard the bad ideas (for example Solidity) sooner. WASM may one day be ubiquitous in all kinds of areas, including smart contracts. Safe, formally verifiable languages, suitable for smart contracts might target WASM - or not.

**Comment by mradkov** [comment]
@peterjoel I can agree with you about the Solidity part.

I also think inventing a new language  `Move`  part is not necessary as every language that can be formally verified could be compiled to WASM, which in this case would have been a good choice.

**Comment by mjrulesamrat** [comment]
Agreeing with @peterjoel , They are on to something.

> First-class resources are a very general concept that programmers can use not only to implement safe digital assets but also to write correct business logic for wrapping assets and enforcing access control policies. The safety and expressivity of Move have enabled us to implement significant parts of the Libra protocol in Move, including Libra coin, transaction processing, and validator management.

Quoting from official _Move_ paper.

**Comment by kivutar** [comment]
From what I can read from the white paper Move is very different from Solidity. I think that the equivalent of ERC20 will be implemented differently. Take a look at the Currency module.

**Comment by plimerence** [comment]
why not use py?

**Comment by shannon1916** [comment]
@peterjoel Words are not precise. I just wonder is it necessary to develop a new VM for the blockchain.

**Comment by TechniumUnlimited** [comment]
I propose to use Python

**Comment by richardmatheson** [comment]
@shannon1916 WASM allows a whole host of other things that are not necessarily desirable for smart contracts or other blockchain applications - it's designed as a very general purpose bytecode for everything. Ethereum's VM has widely known issues - they actually cover why they didn't use EVM in the Libra white paper.

> However, the expressivity of the EVM has opened the door to expensive programming mistakes. Like
StrawCoin, the Ether currency has a special status in the language and is implemented in a way
that enforces scarcity. But implementers of custom assets (e.g., via the ERC20 [15] standard) do not
inherit these protections (as described in (2)) — they must be careful not to introduce bugs that
allow duplication, reuse, or loss of assets. This is challenging due to the combination of the indirect
representation problem described in (1) and the highly dynamic behavior of the EVM. In particular,
transferring Ether to a smart contract involves dynamic dispatch, which has led to a new class of bugs
known as re-entrancy vulnerabilities [16]. High-profile exploits, such as the DAO attack [17] and the
Parity Wallet hack [18], have allowed attackers to steal millions of dollars worth of cryptocurrency.

So Move and Move IR are designed to limit unnecessary expressiveness to protect security.

**Comment by gilescope** [comment]
It would be excellent if Move was a strict subset of an existing language that supported move semantics intrinsically. That way we could use a powerful IDE from the get go.

**Comment by tycooperaow** [comment]
Yeah python would have been a good use for this instead of creating a new language

**Comment by taewookim** [comment]
+1 Python

**Comment by kevinwolfcr** [comment]
Why not ReasonML? 🤷🏻‍♂️

**Comment by TechniumUnlimited** [comment]
Python++

**Comment by gazhayes** [comment]
They should use the K framework, or at least build something that can be formally verified. Anything else is going to end up being a cluster fk like solidity.

For anyone interested, Meredith Patterson is who's research you want to look into when thinking about language security.

**Comment by leewardbound** [comment]
Should have just used Italian, my favorite and objectively the best language in every way

**Comment by richardmatheson** [comment]
Thinking about it, adapting Visual Basic 6 would have made more sense.

**Comment by StefansArya** [comment]
We need to think again about ActionScript3

**Comment by ltfschoen** [comment]
Move technical paper - https://developers.libra.org/docs/move-paper

**Comment by ericnakagawa** [comment]
Hey folks, if you'd like to discuss our choice for smart contract language, please start a thread on https://community.libra.org .
