### ISSUE TITLE
[cluster_test] Do not print health checks when everything is ok

### ISSUE THREAD

**Issue by andll** [libra/libra#1244]
Currently when experiment runs cluster-test output is very verbose, mostly because `HealthCheckRunner::run` prints a lot of stuff on every tick.
Instead of printing it every time, `run` should probably take boolean arg like `print_on_failure` and only print output when this healthcheck failed.

One caveat is that health checker is currently not aware of what validators are affected by experiment. It instead returns list of failed validators and calling code can bi-sect it with list of validators under experiment, in order to make decision on whether test failed or not.

https://github.com/libra/libra/blob/e98af2dae812b7da1024d215321ab7d05aa5522c/testsuite/cluster-test/src/main.rs#L446

One solution is instead of returning list of failed validators, just pass list of validators under experiment into health check, and make HealthCheck::run returning `failure::Result<()>`

**Comment by ankushagarwal** [comment]
@andll  : I was wondering if there is a way for me to run cluster-test without an AWS account? Based on https://github.com/libra/libra/blob/master/testsuite/cluster-test/README.md it seems that cluster-test can only be run on AWS

Or maybe I can first work on #1219 so that I can run cluster-test against local libra swarm and then address this issue.

WDYT?

**Comment by andll** [comment]
We should get you AWS access anyway, and its good if you try to go through setting up your own small aws cluster too... (Maybe @bschwab can help with access, I am not sure who is managing this)
