### ISSUE TITLE
[consensus] byzantine OOM attacks on block tree

### ISSUE THREAD

**Issue by zekun000** [libra/libra#1325]
Attack: Today we accept arbitrary proposals for the current round as long as it's from primary proposer, malicious proposers could send as many proposals as they want and eventually make honest nodes out of memory.

Solution: We should only keep the block voted for and reject any proposals for the same round, but we're also willing to replace it with another one which has the QuorumCert. Note only one block at the same round could have a QuorumCert.

**Comment by bmaurer** [comment]
If a proposer proposes a block in round R, they have to present a proof of round R+1 being over, right? This seems to suggest an even stronger property -- that just based on the incoming RPC (without making a sync / etc) once we see a proposal we can safely discard proposals from previous rounds, as long as we haven't voted on them.

It might also be interesting to think about situations in which there is a long growing block tree. One thought on how byzantine validators might trick a victim into seeing an ever growing tree: imagine a victim V is isolated from the network (so to the rest of the network they are offline). The adversary controls f-1 nodes. Whenever the adversary proposes a block on the real network in round R, and it also controls the R+1 proposer, it doesn't make a proposal, causing the round to timeout. Thus the attacker gets a round certificate on round R. The attacker proposes blocks in round R+1 to the victim. This seems like it'd create an infinitely growing chain.

Admittedly this is an extreme case but it's interesting to think about how bad resource exhaustion could get. I wonder if some simple heuristics could help. For example:

1) If you get a proposal B and B.round > B.qc.last_committed_round + 100, only accept B if it proposes no transactions (since proposers have to follow this it would be a protocol constant)
2) Have a config value max_round_delta_to_vote that refuses to vote for a block if B.round > B.qc.round + max_round_delta_to_vote

This would mean that your worst case memory/disk usage would be 100*max_block_size + max_round_delta_to_vote*empty_block_size.

**Comment by zekun000** [comment]
@bmaurer I don't get how to get an ever-growing chain, you can have an ever growing **tree** if you control **all** the proposers because of no qc formed.

my gut feel is any attempt to limit the block tree growth would kill the theoretic liveness.

1. doesn't help the block growth, empty blocks are still blocks.
2. will kill liveness if we timeout 100 rounds.

**Comment by bmaurer** [comment]
Sorry -- you're right it'd be a tree not a chain. But as a validator you'd have to keep every block you've voted on (i.e. the leafs of the trees). You can't discard blocks until you commit at a higher round.

> doesn't help the block growth, empty blocks are still blocks.

Still greatly reduces the amount of local storage if the block is empty vs having 1 MB or more of transactions.

> will kill liveness if we timeout 100 rounds.

We're still live in this case, we just need to commit an empty block before we take more transactions. It seems like we could tune the number to a point high enough that we're unlikely to trigger yet low enough that we can survive that number of empty blocks.

**Comment by davidiw** [comment]
@zekun000 what did you ever do here?
