### ISSUE TITLE
[Roadmap][Move VM] Internal Improvements

### ISSUE THREAD

**Issue by gc3** [libra/libra#1458]
This issue tracks several features of the Move VM that are internal to the operation of the blockchain. In addition to ongoing efforts to clean up and simplify the VM code, we need the following features:

- Logging: The VM needs to be able to report unusual conditions, including not only errors but also various kinds of unexpected events (e.g., perhaps a transaction that takes much longer than usual to process).
- Monitoring: We need to monitor the regular activity of the VM (e.g., memory use, transaction rate, etc.) so that node operators can detect and respond to potential problems.
- Gas mechanics: Gas metering is a key feature to account for the resources used during transaction processing. The work here includes storing gas parameters on-chain, distributing gas transaction fees, and cleaning up the implementation of gas accounting within the VM.
- Block metadata: Each block on chain will include metadata to record things like a timestamp, a hash of the block, and the address of the proposer. This spans across multiple components besides the VM, but we are tracking it as a VM feature.

**Comment by bob-wilson** [comment]
Work on logging and monitoring is ongoing and not yet complete.

Block metadata is now complete, starting with https://github.com/libra/libra/pull/1068 followed by various other changes up to the more recent work in https://github.com/libra/libra/pull/1489 and https://github.com/libra/libra/pull/1611.

Gas functionality is mostly done. Some of the more recent work involved setting up gas fee distribution (https://github.com/libra/libra/pull/992), recording a schedule of gas costs on-chain (https://github.com/libra/libra/pull/1406), and cleaning up the implementation in the VM (https://github.com/libra/libra/pull/1637). There will be some adjustments to gas pricing later when we have more accurate measurements of some costs, but otherwise, the last thing that we're waiting for is to enable the distribution of gas fees (https://github.com/libra/libra/pull/1809).

**Comment by bob-wilson** [comment]
Some additional items:

- On-chain transaction whitelist: the VM currently has a hardcoded whitelist of allowed transactions. It would be better to store that list as an on-chain resource so that it is easier to change.
- Support direct writeset transactions that will enable updating the on-chain content for things like the core Move modules.

**Comment by bob-wilson** [comment]
The on-chain transaction whitelist is done in #2932

**Comment by bob-wilson** [comment]
Support for direct writeset transactions is done in #3299 
The remaining work here is for logging and monitoring.

**Comment by bob-wilson** [comment]
After reviewing the current logging code in the VM, we have concluded that what we already have is fine. We also reviewed the monitoring code and updated it to follow the same conventions as the rest of the Libra system in #3600 

We will continue to make improvements to the VM, but the work tracked by this issue is now complete.
