### ISSUE TITLE
[network][noise] Noise static private keys must zeroize-on-drop.

### ISSUE THREAD

**Issue by phlip9** [libra/libra#1536]
To match the API from [`mcginty/snow`](https://github.com/mcginty/snow) (our current Noise library), we are copying out secret key material from the safe `x25519_dalek::StaticSecret` (contained in our `X25519StaticPrivateKey`) and placing it into a `snow::Keypair`.

Currently `mcginty/snow` doesn't appear to zeroize-on-drop the secret key material. We need to ensure two things:

1. Copying out and placing the key material into the `snow::Keypair` doesn't leave any key material hanging around, unzeroed.
2. `snow::Keypair` zeroizes-on-drop (https://github.com/mcginty/snow/issues/2).

The offending code:

```rust
impl NoiseConfig {
    /// Create a new NoiseConfig with the provided keypair
    pub fn new(keypair: (X25519StaticPrivateKey, X25519StaticPublicKey)) -> Self {
        let parameters: NoiseParams = NOISE_IX_PARAMETER.parse().expect("Invalid protocol name");
        let keypair = Keypair {
            private: keypair.0.to_bytes().to_vec(),  // <---
            public: keypair.1.to_bytes().to_vec(),   // <---
        };
        Self {
            keypair,
            parameters,
        }
    }

    // ..
}
```

There are likely two paths forward:

1. Upstream changes to `snow` so that its key material zeroizes-on-drop.
2. Alternatively, we could take this as an opportunity to reduce our attack surface by writing our own Noise handshake logic so that it only supports the specific handshakes and crypto primitives that we require. For example, [NoiseExplorer's IK in Rust](https://noiseexplorer.com/dcafc3ab-dddf-074c-8ecb-be14de302b21) is ~= 1k loc.

cc @gedigi @bmwill @huitseeker @mimoo

**Comment by bmwill** [comment]
One very important thing to note is that implementing zeroize-on-drop is not sufficient. Move semantics in Rust result in things being memcpy'd around the place, leaving the source bits untouched. Really what we'll want to do is have the private key material be in some `Box<[u8]>` type struct on the heap so that moving around a key doesn't result in a bunch of copies of the private key material all over the stack. We'll then need to be extremely careful about how we get the key material into the `Box` to ensure that if the key ever existed on the stack that it is zero'd out.

**Comment by huitseeker** [comment]
Note for reference that the current implementation of our x25519 keys do not suffer from this problem, since they wrap the zeroize-implementing x25519-dalek:
https://github.com/libra/libra/blob/3ac6bb8f8bab534eb4005e23d4fe8e68b0fdc27c/crypto/crypto/src/x25519.rs#L69-L72

(this is relevant to current attempts to change this, e.g. #3951 /cc @mimoo )

As we store this key in the `NoiseConfig` unchanged, this reasoning carries over there too:
https://github.com/libra/libra/blob/3ac6bb8f8bab534eb4005e23d4fe8e68b0fdc27c/network/noise/src/lib.rs#L31-L34

So, outside of what @bmwill mentioned (i.e. we also need to `Pin<>`), I'm not sure I understand what's left to do for this one. Should we close?

**Comment by phlip9** [comment]
@huitseeker I don't think the situation is different even with @mimoo's diff. As @bmwill correctly points out, `zeroize` won't help us since we're still moving `x25519::PrivateKey`s around directly \[1\], as rust will just `memcpy` them and leave sensitive data littered around the stack (since `Drop` isn't called after move).

Ideally, there is only one location in memory that contains the key material. There are more mitigations we could add on top, like those described in the [`secrets`](https://crates.io/crates/secrets) crate (or we could just use this crate directly, though it pulls in all of libsodium... which is pretty hefty).

For now, I think the best min effort/min threat tradeoff is to just always wrap the key material in an `Arc` and provide read-only accessors (which i believe we do already). x25519-dalek already handles zeroizing on drop, so we should be good there. Then the tricky part is cleanly putting the key material into the `Arc` key container w/o littering the stack.

```rust
// mod x25519;

pub struct PrivateKey(Arc<x25519_dalek::StaticSecret>);
```

\[1\]: https://docs.rs/zeroize/1.1.0/zeroize/#stackheap-zeroing-notes

**Comment by huitseeker** [comment]
@phlip9 So, there are two components:
- having private keys in controlled memory locations only,
- zeroizing the memory location on drop,

And for security, we're in agreement you need both. Zeroize is a solution to the second issue, not the first, on that we're again in agreement. There are distinct tools means to help the first issue (e.g. [`Pin`](https://doc.rust-lang.org/std/pin/index.html) or, as you mentioned, secrets). 

I though the scope of this issue was squarely on zeroizing on drop. It made sense to me, since even if it's only a partial solution, it's a necessary component of the solution.

Should we open another issue for the memory copy control? I have some thoughts on the `Arc` suggestion, which has been floated previously, but I'd rather attack the problem piecewise.

**Comment by phlip9** [comment]
Ok, sounds good! Let's open a new issue describing the first component and its potential solutions, since dalek already handles the second part. Do you want to handle creating the new issue? I'll close this one since it's no longer relevant.
