### ISSUE TITLE
[Bug]build script failed, must exit now', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.40/src/lib.rs:832:5

### ISSUE THREAD

**Issue by wbm0701** [libra/libra#154]
CMake Error at CMakeLists.txt:8114 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression

thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.40/src/lib.rs:832:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by wqfish** [comment]
Hi @wbm0701 please try installing the latest version of `cmake`.

**Comment by chenyudev** [comment]
I got the same build error.

I had run `./scripts/dev_setup.sh` and `cargo build`.

OS Version: macOS 10.15 beta2
Go: go1.12.4 darwin/amd64
cmake: 3.14.5 or 3.15-rc

error is below:
`error: failed to run custom build command for `libtitan_sys v0.0.1 (https://github.com/pingcap/rust-rocksdb.git?rev=8d6cda70f22da2cd15ed7351fcffa9add3444595#8d6cda70)`

Caused by:
  process didn't exit successfully: `/Users/chen/sourcetree/libra/target/debug/build/libtitan_sys-0e1aa4108f8f088a/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan" "-DROCKSDB_DIR=/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb" "-DWITH_TITAN_TESTS=OFF" "-DWITH_TITAN_TOOLS=OFF" "-DWITH_ZLIB=ON" "-DWITH_BZ2=ON" "-DWITH_LZ4=ON" "-DWITH_ZSTD=ON" "-DWITH_SNAPPY=ON" "-DCMAKE_INSTALL_PREFIX=/Users/chen/sourcetree/libra/target/debug/build/libtitan_sys-36c7dd4a027b620e/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- The C compiler identification is AppleClang 11.0.0.11000020
-- The CXX compiler identification is AppleClang 11.0.0.11000020
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found snappy: /Users/chen/sourcetree/libra/target/debug/build/snappy-sys-e1e69101c91499f8/out/build/libsnappy.a
-- Found bzip2: /Users/chen/sourcetree/libra/target/debug/build/bzip2-sys-c87b19b7c69fbc99/out/lib/libbz2.a
-- Found lz4: /Users/chen/sourcetree/libra/target/debug/build/lz4-sys-d724b89235dc6fd2/out/liblz4.a
-- Found zlib: /usr/lib/libz.dylib
-- Found zstd: /Users/chen/sourcetree/libra/target/debug/build/zstd-sys-cfe41a66a86244fb/out/libzstd.a
-- Performing Test HAVE_SSE42
-- Performing Test HAVE_SSE42 - Success
-- Performing Test HAVE_THREAD_LOCAL
-- Performing Test HAVE_THREAD_LOCAL - Success
-- Enabling RTTI in Debug builds only (default)
-- Performing Test HAVE_FALLOCATE
-- Performing Test HAVE_FALLOCATE - Failed
-- Performing Test HAVE_SYNC_FILE_RANGE_WRITE
-- Performing Test HAVE_SYNC_FILE_RANGE_WRITE - Failed
-- Performing Test HAVE_PTHREAD_MUTEX_ADAPTIVE_NP
-- Performing Test HAVE_PTHREAD_MUTEX_ADAPTIVE_NP - Failed
-- Looking for malloc_usable_size
-- Looking for malloc_usable_size - not found
-- Looking for sched_getcpu
-- Looking for sched_getcpu - not found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/chen/sourcetree/libra/target/debug/build/libtitan_sys-36c7dd4a027b620e/out/build
running: "cmake" "--build" "." "--target" "titan" "--config" "Debug" "--"
Scanning dependencies of target titan
[  4%] Building CXX object CMakeFiles/titan.dir/src/base_db_listener.cc.o

--- stderr
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.cc:1:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.h:3:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/db_impl.h:4:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/db_impl.h:23:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/compaction_job.h:24:
/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/internal_stats.h:111:5: error: declaration shadows a variable in namespace 'rocksdb' [-Werror,-Wshadow]
    WAL_FILE_BYTES,
    ^
/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/include/rocksdb/statistics.h:191:3: note: previous declaration is here
  WAL_FILE_BYTES,   // Number of bytes written to WAL
  ^
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.cc:1:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.h:3:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/db_impl.h:4:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/db_impl.h:23:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/compaction_job.h:24:
/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/internal_stats.h:112:5: error: declaration shadows a variable in namespace 'rocksdb' [-Werror,-Wshadow]
    WAL_FILE_SYNCED,
    ^
/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/include/rocksdb/statistics.h:190:3: note: previous declaration is here
  WAL_FILE_SYNCED,  // Number of times WAL sync is done
  ^
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.cc:1:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.h:3:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/db_impl.h:4:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/db_impl.h:23:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/compaction_job.h:24:
/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/internal_stats.h:113:5: error: declaration shadows a variable in namespace 'rocksdb' [-Werror,-Wshadow]
    BYTES_WRITTEN,
    ^
/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/include/rocksdb/statistics.h:126:3: note: previous declaration is here
  BYTES_WRITTEN,
  ^
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.cc:1:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.h:3:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/db_impl.h:4:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/db_impl.h:23:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/compaction_job.h:24:
/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/internal_stats.h:114:5: error: declaration shadows a variable in namespace 'rocksdb' [-Werror,-Wshadow]
    NUMBER_KEYS_WRITTEN,
    ^
/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/include/rocksdb/statistics.h:119:3: note: previous declaration is here
  NUMBER_KEYS_WRITTEN,
  ^
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.cc:1:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.h:3:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/db_impl.h:4:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/db_impl.h:23:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/compaction_job.h:24:
/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/internal_stats.h:115:5: error: declaration shadows a variable in namespace 'rocksdb' [-Werror,-Wshadow]
    WRITE_DONE_BY_OTHER,
    ^
/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/include/rocksdb/statistics.h:196:3: note: previous declaration is here
  WRITE_DONE_BY_OTHER,  // Equivalent to writes done for others
  ^
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.cc:1:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.h:3:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/db_impl.h:4:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/db_impl.h:23:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/compaction_job.h:24:
/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/internal_stats.h:116:5: error: declaration shadows a variable in namespace 'rocksdb' [-Werror,-Wshadow]
    WRITE_DONE_BY_SELF,
    ^
/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/include/rocksdb/statistics.h:195:3: note: previous declaration is here
  WRITE_DONE_BY_SELF,
  ^
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.cc:1:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.h:3:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/titan/src/db_impl.h:4:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/db_impl.h:23:
In file included from /Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/compaction_job.h:24:
/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/db/internal_stats.h:117:5: error: declaration shadows a variable in namespace 'rocksdb' [-Werror,-Wshadow]
    WRITE_WITH_WAL,
    ^
/Users/chen/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/8d6cda7/librocksdb_sys/libtitan_sys/../rocksdb/include/rocksdb/statistics.h:198:3: note: previous declaration is here
  WRITE_WITH_WAL,       // Number of Write calls that request WAL
  ^
7 errors generated.
make[3]: *** [CMakeFiles/titan.dir/src/base_db_listener.cc.o] Error 1
make[2]: *** [CMakeFiles/titan.dir/all] Error 2
make[1]: *** [CMakeFiles/titan.dir/rule] Error 2
make: *** [titan] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /Users/chen/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.40/src/lib.rs:832:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed`

**Comment by icarter09** [comment]
@wbm0701 did @wqfish comment help you fix your issue?

**Comment by bmwill** [comment]
The external dependencies needed to build Libra have been simplified and should only require Rust now so this shouldn't be an issue anymore on master. If it is, please let us know.
