### ISSUE TITLE
[style] `rustfmt` default formatting for use imports changed

### ISSUE THREAD

**Issue by phlip9** [libra/libra#1587]
I noticed recently that `rustfmt` wasn't merging my use imports anymore. For most of the libra codebase's lifespan, running `rustfmt` would do the following change:

Before `cargo fmt`:

```rust
use std::sync::Arc;
use std::sync::Mutex;
```

After `cargo fmt`:

```rust
use std::sync::{Arc, Mutex};
```

However, it appears that the current beta/stable (?) `rustfmt` has adopted a policy of not merging imports and allowing the user to always control merging. Maybe it was the nightly `rustfmt` that had the non-standard default? Not sure.

Anyway, after our transition to beta compiler, code-style has diverged in many (~30-40) files. For example, in `network/src/validator_network/network_builder.rs`, we can see merged and unmerged imports sitting right next to each other:

```rust
use std::{
    collections::HashMap,
    sync::{Arc, RwLock},
    time::Duration,
};
use tokio::runtime::TaskExecutor;
use tokio::timer::Interval;
```

As a temporary fix for myself, I added the [unstable "merge_imports" option](https://github.com/rust-lang/rustfmt/issues/3362) to my local `libra/rustfmt.toml`, updated my nightly (since beta doesn't allow unstable rustfmt options), and changed my vim config to use nightly rustfmt:

```diff
diff --git a/libra/rustfmt.toml b/libra/rustfmt.toml
index 80eeb405..9700e576 100644
--- a/libra/rustfmt.toml
+++ b/libra/rustfmt.toml
@@ -1,2 +1,3 @@
 edition = "2018"
 use_field_init_shorthand = true
+merge_imports = true
```

```sh
$ rustup update
$ rustup component add rustfmt --toolchain nightly
```

Then in my vim autoformatting settings, changed the rustfmt command to:

```sh
$ rustup run nightly rustfmt
```

Note: it appears the "merge_imports" option is currently unstable, so we probably can't enable this right away: https://github.com/rust-lang/rustfmt/issues/3362

Any thoughts @bmwill @sunshowers @metajack ? I'm not sure what is the best future-proof way we can tackle this, at least without hacky quick fixes like above.

**Comment by bmwill** [comment]
I don't really think this is that big of a deal and I knew about this because I was the one that moved us to beta and had to remove the `merge_imports` item from the rustfmt.toml file. Given that its an unstable feature we can't use it on stable so I think we should just wait till its stabilized (course it seems like there are a few corner cases that are preventing it from being stabilized). Given that a lot of people rely on their editors doing the formatting i don't think this is a good thing to try and force everyone to run rustfmt using a nightly toolchain.
