### ISSUE TITLE
RFC: LedgerInfo to keep block metadata

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#1604]
## Main data-types today
Below are the structs we're using today:
```
/// BlockInfo keeps the metadata about the executed proposal.
pub struct BlockInfo {
   epoch: u64,
   round: Round,
   id: HashValue,
   executed_state_id: HashValue,
   version: Version,
   timestamp_usecs: u64,
   next_validator_set: Option<ValidatorSet>,
}

/// A validator that sends out a vote signs both the proposal and its parent (used by TCB).
pub struct VoteData {
   proposed: BlockInfo,
   parent: BlockInfo,
}

/// LedgerInfo includes the information about the committed block as well as the hash of the vote.
/// In case there is no commit LedgerInfo fields are all zeroes, except for `consensus_data_hash`.
pub struct LedgerInfo {
   version: Version,
   transaction_accumulator_hash: HashValue,
   consensus_data_hash: HashValue, // hash of VoteData
   consensus_block_id: HashValue,
   epoch: u64,
   timestamp_usecs: u64,
   next_validator_set: Option<ValidatorSet>,
}

/// QuorumCert includes both the vote data about the certified block as well as the ledger info of
/// the committed block.
pub struct QuorumCert {
   vote_data: VoteData,
   signed_ledger_info: LedgerInfoWithSignatures,
}
```
## The proposal
The initial design of the accumulator tried to decouple the internal details of consensus protocol from client-visible APIs. `LedgerInfo` that is exposed to the clients didn't have any mention of blocks at all. However, we soon realized that this approach might not be convenient.
We had to add things like `consensus_block_id`, just to be able to understand and compare the latest committed transaction in storage with the root of consensus tree upon restart.

This proposal is taking an additional step further towards a "block aware" storage.

```
/// LedgerInfo keeps both the vote information and the commit information if a new vote is
/// going to generate commit.
pub struct LedgerInfo {
   commit_info: BlockInfo, // relevant for the clients.
   consensus_vote_info: VoteData, // vote information that is relevant for consensus only.
}

/// QuorumCert is just a LedgerInfo that is signed by the quorum of validators.
pub type QuorumCert = LedgerInfoWithSignatures;
```

### What do we change?
* `LedgerInfo` already used to keep almost all the information of the committed block (with different field names), except round. This proposal is making it explicit: `LedgerInfo` committed info keeps all the information about the metadata of the committed block.
* `LedgerInfo` used to keep the hash of the `VoteData`: this proposal changes it to keep `VoteData` itself, which makes `QuorumCert` and `LedgerInfoWithSignatures` the same thing.

### Why is it good?
* Unification and simplification of the data structures.
* `LedgerInfo` with all the `BlockInfo` information makes it easier to compare between LedgerInfos via (`epoch, round`) comparison instead of using timestamps, which gets ugly for artificial empty blocks (e.g., `NIL` blocks).
* A validator that receives a `LedgerInfo` can treat it the same way it used to treat a `QuorumCert`. We used to have a somewhat absurd situation with a validator not being able to commit a block, which is certified by a `LedgerInfo`, because that validator doesn't have a third QC for forming a 3-chain (related to a StateSync byzantine attack). This proposal solves it.

### Problems?
* The size of `LedgerInfo` now grows about x3 (from keeping info about one block metadata to keeping info about 3 blocks). As far as I understand it's not a problem because the size of `LedgerInfo` is negligible in comparison with the size of signatures that are certifying it.
* In case we change the consensus protocol in future, the `consensus_vote_info` struct of `LedgerInfo` would have to change. I hope it's not a problem for the clients, because they don't have a way to use it today anyway.

**Comment by davidiw** [comment]
Hmm...

Maybe
`
pub struct LedgerInfo {
  proposed: BlockInfo,
  parent: BlockInfo,
  committed: BlockInfo,
}
`

I don't think we need VoteData structure any more.

I think at this point, making this optimization to make the code more accessible seems like a win. While there may be a counter argument in not moving toward this direction, I would argue we should focus on tidying our interfaces at a later date as we approach V1, as a lot can happen between now and then and we shouldn't over pivot on that at this point in time.

**Comment by dmitri-perelman** [comment]
@davidiw yea, that's a good point. The only reason to separate out the VoteData as a separate structure would be to emphasize the distinction between the internal vote data and the external facing commit data.

**Comment by zekun000** [comment]
committed_info should be an Option<BlockInfo> right?

**Comment by aching** [comment]
This is an interesting proposal, thank you for sharing it.  IIUC, there are 2 fundamental ideas here:
1) Expose a unit of a block of committed transactions vs a count of committed transactions.
2) Exposing consensus data structures into the committed data structure (to be ignored by clients)

Regarding 1, I am in favor of this direction.  Thinking about committed blocks from a state synchronization perspective, adding a small amount of block metadata overhead to the LedgerInfo (i.e. block height) allows one to sync to a block height rather than a version such that consensus can sync up on blocks.  Blocks are an optimization to group transactions that I don't see us going away from any time soon so exposing it seems reasonable.  From a granularity perspective on full nodes, syncing blocks of committed transactions as opposed to ranges of transactions is less flexible, but reasonable.  If this ever truly became an issue due to extremely slow syncers, we could still sync to individual versions by including their proofs from a block LedgerInfo, but I would leave that to future work.

Regarding 2, I am hesitant to move toward this direction.  IMO, LedgerInfo was originally designed to have 2f+1 voting power signing off on a commit and without leaking information about the consensus protocol and its independent fields.  The main benefits of this type of approach is that clients aren't confused by any non-essential data in the LedgerInfo and any changes to the consensus protocol wouldn't require changes in the way that clients verify the 2f+1 signatures of committed data.  Full nodes that verify consensus would have to be aware of consensus changes, but lighter clients - e.g. say those that just keep track of the time or only do network key discovery wouldn't care.

> Unification and simplification of the data structures.

I agree that today the structures are partially unified and it is appealing to either fully unify them or to fully separate them.  

> LedgerInfo with all the BlockInfo information makes it easier to compare between LedgerInfos via (epoch, round) comparison instead of using timestamps, which gets ugly for artificial empty blocks (e.g., NIL blocks).

I think that block height would be simpler way to compare between LedgerInfos and keep round outside of the client's information.

**Comment by dmitri-perelman** [comment]
@aching thanks for the comments! I really like the new dichotomy: the axes of block awareness and the axes of consensus awareness in the LedgerInfo.
My current understanding is as follows:
* Block-awareness in LedgerInfo is a good thing and we all agree about that
* `round` vs.`height` is an interesting comparison. I agree that height is less consensus specific. Today we don't have it but it could be added back relatively easily. The (epoch, round) today can be used by consensus for LI comparison. Height could definitely serve the same purpose. Tbh I can't see that consensus would get rid of monotonically increasing rounds in a foreseeable future, so I'd say if that's the only thing that prevents us from unifying the data structures, I'd go with the `BlockInfo` being unified.
* `VoteData` as part of the `LedgerInfo` is a more complicated topic.
   * We all agree that the clients should not depend on the changes in the protocol.
   * The problem is that clients verify signatures by calculating the hash of the LCS serialization of the `LedgerInfo` structure, so in case we change some consensus-specific parameters in `VoteData`, old clients would not be able to calculate the same hash and thus fail the signatures.
   * We could still keep the `LedgerInfo` with `VoteData`, but we'd then need to talk about different representations of this LedgerInfo: a "verbose" representation keeps all fields in a flat fashion, while a "concise" representation is keeping the hash of the vote_data. The clients would receive the concise representation, while validators could use the full representation.
   * All in all I'm not sure I feel confident enough to do replace the hash with the data today (unlike `BlockInfo` being part of `LedgerInfo`, which I feel is a pretty strong win in comparison to the status quo)

**Comment by aching** [comment]
Sounds like a plan to add the block awareness and punt on adding more consensus specific data to LedgerInfo for now.  I'd be okay with round for now for code simplicity but would replace its use case with height in the future if we move to a world where LedgerInfo is purely necessary committed block information (epoch, executed_state_id, version, height, timestamp_usecs, next_validator_set) and LedgerInfo and QCs are separately signed structures.
