### ISSUE TITLE
[Feature Request] integration with mobile money platforms

### ISSUE THREAD

**Issue by elemanhillary** [libra/libra#174]
# 🚀 Feature Request

- There are already existing mobile money platforms from all over the globe that even people leaving in extreme poverty use. Libra when integrated with those platforms we shall reach the ultimate goal and mission of serving even the less fortunate ones say put a USSD integration for non-smart phone users.

## Motivation

**Is your feature request related to a problem? Please describe.**
- Reach the less fortunate who cannot afford a smartphone and integrate a USSD app

## Pitch

**Describe the solution you'd like**
Since we have an app for smartphone users let's have a USSD application.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
- As soon as I master mt RUST journey

**Comment by bmaurer** [comment]
Empowering people across the globe is absolutely part of Libra's mission. However, this repository is designed to contain Libra Core, the infrastructure behind Libra. Things such as a mobile wallet would be built on top of this software. Since this is out of scope, I'm going to close the task, but we'd love to have you involved in the community!
