### ISSUE TITLE
do i need to copy or move on none resourse type: address in earmarked example?

### ISSUE THREAD

**Issue by aihuawu** [libra/libra#185]
I find if I use copy or move in the following code, it will work.
but recipient is just an address, why do I need it?
see the comment below.
  
public create(coin: R#LibraCoin.T, recipient: address) {
    let t: R#Self.T;

    t = T {
      coin: move(coin),
      recipient: recipient, // not work
      //recipient: copy(recipient), // work
      //recipient: move(recipient), // work
    };

    move_to_sender<T>(move(t));
    return;
  }

**Comment by starzhouchina** [comment]
How to test and run a move code?

**Comment by aihuawu** [comment]
2 ways to do it.
 
1) use cargo
cargo run -p compiler -- create_account_script.mvir
cargo test -p functional_tests move_getting_started_examples

2) command line. To compile, see below. 
To run use the above and put your code in directory functional_tests.

$LIBRA_DIR/target/debug/compiler -h

**Comment by sblackshear** [comment]
Yes, every usage of a variable must be wrapped in an explicit `copy` or `move`. Variables of unrestricted type (such as `address`) can be both copied and moved. Variables of resource type can only be moved.

The Move IR requires the programmer to be explicit about this because it is a thin wrapper around the bytecode. `copy`'s compile to a `CopyLoc` instruction, and `move`'s compile to a `MoveLoc` instruction. In a higher-level Move source language, we could use liveness analysis to infer whether a `move` or `copy` is intended based on whether the variable in question is used again. But the IR is a low-level language intended for testing the bytecode verifier/VM. To exercise the bytecode verifier, we need to be able to write (e.g.) `y = move(x); z = move(x)` and check that the bytecode verifier rejects the code.

**Comment by aihuawu** [comment]
Thanks.
Now I understand it since it is low level.
Do you have any timeline when the alpha version of move source language will be available?
You don't have to have the verify work in the alpha version.

It is good to play with the Move IR to understand the concept.
But to be serious in developing an application, I would rather deal with move source high level language even if it is just in alpha stage.

**Comment by starzhouchina** [comment]
Thank you @aihuawu and  @sblackshear.
Okay,  I can compile and learn it followed by your suggestions. Very exciting.
If a variable is resource variable , only using move instruction.  and strict  a  bytecode verifier. 
If a address variable, can  use move and copy ,and can use it again.
Thank  two advancing  and nice specialist!

**Comment by aihuawu** [comment]
@starzhouchina, you are welcome.
I am also learning and hope we can learn from each other.
The move concept for resource is nice.

**Comment by starzhouchina** [comment]
Very nice , We can learn from each other.  Move is secuity and  verfier language for higher  secuity  need situations

**Comment by icarter09** [comment]
@aihuawu sounds like your issue was addressed. Can you close this issue? Thanks.
