### ISSUE TITLE
[Bug] Reconnect account problem

### ISSUE THREAD

**Issue by zb188** [libra/libra#188]
# 🐛 Bug

## Restart the connection to testnet, the query account list is empty, has been created before, after I perform the creation operation, the account that was queried is still created.

**Comment by kphfb** [comment]
Hi @zb188, when a wallet is created, it creates a mnuemonic file locally.  When you create accounts using this file, it will ALWAYS create the same accounts in the same order - essentially, it will generate the same keypairs.  If you want to create truly new accounts, you must delete the mnuemonic file that is in the local directory.  Otherwise, you will keep getting the same accounts in the same ordering

**Comment by lyuyuan92** [comment]
@kphfb Hi! The `ClientProxy` struct has an `accounts` field which, due to its comment, represents the created accounts. But with the current implementation of the `new` method, this field will always be an empty `Vec<AccountData>`.
https://github.com/libra/libra/blob/bd8e6dc5434d39bd6b56a3502076353d0787a7ef/client/src/client_proxy.rs#L116-L152
It seems to me that `accounts` should be initialted if a mnemonic_file is given to the `Args`
Am I right about this?

**Comment by kphfb** [comment]
Hi @lyuyuan92, the way it works with a mnuemonic file is that you basically have a consistent seed.  So if you are using the same mnuemonic file each time you start the client, you will "create" the same accounts.  Since you now have the same keypair as you had previously, the accounts will have already had some actions performed with them (assuming that you did some actions on a previous run of the client).  The mnuemonic file does not care/know about how many accounts (aka keypairs) were generated on previous runs, so it can't just regenerate all of them (although, we have talked about doing this at some point - but the save/reload functionality basically does this already).  So let's say you generate 3 accounts, A, B, C on the first run of the client.  When you start the client again, the mneumonic file already exists so it gets loaded again.  Your client when run the second time, loads this file to basically get the same seeds for the random account generation.  So now you generate one account and you'll get A again.  Even though locally it seems like it's a "new" account, on the blockchain you may have already performed actions.  If you were to delete the mnuemonic file before starting the client the second time, you would not get "A" again

**Comment by lyuyuan92** [comment]
Thanks for the explanation! I did realize that if I create accounts after reconnecting my client, I will get my accounts again. It is just a bit nicer (in my opinion) if accounts can be listed after reconnecting.

**Comment by zb188** [comment]
@kphfb Reconnect the client. Since there are already account files before and account list is executed to list the accounts directly, why do you need to execute create to load the accounts again?

**Comment by kphfb** [comment]
@zb188 unless you use the account saving functionality, we don't store how many accounts were created.  So we wouldn't be able to recreate the same number of accounts
