### ISSUE TITLE
coin keeps growing since no way to burn a corn in LibraCoin system module

### ISSUE THREAD

**Issue by aihuawu** [libra/libra#191]
If you go through the code, you can only mint coin and can't burn a coin.
There is a destroy_zero method but the coins in the system keeps growing.

Is this the desired behavior?

**Comment by icarter09** [comment]
@bmwill is this desired behavior?

**Comment by sunshowers** [comment]
Good question! I'm not totally sure, let me forward this to folks who would know.

**Comment by sblackshear** [comment]
Yes, this is intentional. In the production version of Libra core, `LibraCoin.T`'s will only be able to be burned by an Association-controlled account (and will be burned only when the physical backing assets are sold, see the Libra [whitepaper](https://libra.org/en-US/white-paper/#the-libra-currency-and-reserve) for more details on this).

However: in the current testnet, `LibraCoin.T`'s get [burned](https://github.com/libra/libra/blob/master/language/stdlib/modules/libra_account.mvir#L295) in the transaction epilogue because we have not yet implemented the logic for distributing transaction fees.

Note that any user can effectively burn a `LibraCoin.T` by sending it to a random address.
