### ISSUE TITLE
LICENSE needs to be updated.

### ISSUE THREAD

**Issue by 0dayZh** [libra/libra#20]
```
Copyright [yyyy] [name of copyright owner]
```

**Comment by bmaurer** [comment]
Thanks for your diligence and reporting this.

Traditionally one doesn't customize the apache license in this way. e.g. https://svn.apache.org/viewvc/httpd/httpd/trunk/LICENSE?revision=1824973&view=markup

Note that we use SPDX based headers with no copyright date. Because who wants to spend New Years Day updating copyright dates??
