### ISSUE TITLE
[Feature] Adding explicit sender/receive field into AccountEvent 

### ISSUE THREAD

**Issue by thefallentree** [libra/libra#2064]
Right now there is no clear way to determine the sender / receiver on AccountEvent,  one is in the event key (which also contains salt) , and the other field changes meaning base on the Event type. So it is hard to use and it will be great to have an independent event key and explict sender, receiver on an single type "PaymentEvent"

**Comment by sblackshear** [comment]
https://github.com/libra/libra/pull/2075 should make the difference between sent and received events clearly. 

Note that you shouldn't need an explicit sender field for the sent event or an explicit receiver for the received event because you can read these off of the `EventKey` for the stream the event was emitted to.

@runtian-zhou: it looks like it is not very easy to do this from Rust because `EventKey` is [represented](https://github.com/libra/libra/blob/master/types/src/event.rs#L21) as an opaque array of bytes. Would it make sense to change this to reflect the structure of event keys (e.g., `EventKey { creator_address: Vec<u8>, creator_counter: u64 }`)?

It also seems unfortunate that the Rust and Move names/representations of `EventKey` are different (see `guid` [here](https://github.com/libra/libra/blob/master/language/stdlib/modules/libra_account.mvir#L80)) Perhaps Move should also have an explicit `EventKey` type that mirrors the Rust one?.

**Comment by runtian-zhou** [comment]
> It also seems confusing that the Rust and Move names/representations of `EventKey` are different (see `guid` [here](https://github.com/libra/libra/blob/master/language/stdlib/modules/libra_account.mvir#L80)) Perhaps Move should also have an explicit `EventKey` type that mirrors the Rust one?

The main trouble that we have right now is we do not have fixed length bytearray. Thus if we create an explicit `EventKey` type in move, the serialized format will have a length prefix, which will unnecessarily make the event key larger

**Comment by sblackshear** [comment]
> Thus if we create an explicit EventKey type in move, the serialized format will have a length prefix, which will unnecessarily make the event key larger

- Although it's good to keep size in mind, I think the most important thing is ensuring that clients can actually get the information they need from events. If there's a way to help @thefallentree get the info he needs without changing the event representation, that's good too! But let's solve the problem one way or another.
- With that said, I'm confused why adding a move `EventKey` type would change the size of the event key data. In LCS, `guid` is a 40 byte bytearray with a 4 byte length prefix. The struct representation of `EventKey` would be a 32 byte address with 4 byte length prefix and a 8 byte counter. Where is the extra space.

**Comment by ketola** [comment]
> > The main trouble that we have right now is we do not have fixed length bytearray. Thus if we create an explicit `EventKey` type in move, the serialized format will have a length prefix, which will unnecessarily make the event key larger

The sender account address in a transaction is already a fixed-lengths byte array, couldn't similar be used here?

**Comment by sblackshear** [comment]
> The sender account address in a transaction is already a fixed-length byte array (without length info), couldn't similar be used here?

Unfortunately not because account addresses are a distinguished type in the language. What we're discussing here is something more lightweight than changing the language: just adding an `EventKey` struct in the `LibraAccount` module.

**Comment by runtian-zhou** [comment]
I'll add helper functions for EventKey to get the creator. I do afraid that this api will create the illusion that it is the sender of this event, which might not be the case as EventHandle might be moved.

**Comment by bob-wilson** [comment]
@runtian-zhou If there isn't anything else needed, can you close this?
