### ISSUE TITLE
how to authorize one module to call another module as in solidity?

### ISSUE THREAD

**Issue by crabex** [libra/libra#2142]
I want to only allow only one module to call another module.
In ethereum solidity, it is quite easy to do since the sender will change to the calling contract.

Can I change the sender as I do in solidity?

Thanks.

George wu

**Comment by sblackshear** [comment]
Good question. In Eth, there are two kinds of authority: transaction sender authority (i.e., tx.origin) and contract authority (i.e., msg.sender). Because Move has modules (not contracts), it only has the first kind of authority.

Thus, it's not natural to do something like "allow one module to only call another module" in Move. I'm guessing that there is a different/possibly better way to solve your underlying problem (and if you share more details about your use-case, I'm happy to try to weigh in on that!). However, let me try to answer the question as-is.

Let's say that you have modules Parent and Child and desire that only Parent can call `Child.pick_up()`. Two options are:

- You could combine the `Parent` and `Child` modules into a single module, make `pick_up` private, and only call it from the desired procedures of parent.
- Give `Parent` a unique capability that other modules do not have. Here's a somewhat clumsy way to do this

```
module ParentCapability {
  resource Singleton { acquired: bool }
  resource T { addr: address }

  // publish a unique instance of Singleton under the sender's address
  // only works if the sender is a specific address
  public create() {
    let parent_module_addr = // insert address where Parent module is stored here;
    assert(get_txn_sender() == parent_module_addr);

    move_to_sender<Singleton> { acquired: false };
  }

  // acquire an instance of T. Can only be called once
  public get(): Self.T {
    let singleton_ref = borrow_global_mut<Singleton>(get_txn_sender());
    assert(!singleton_ref.acquired);
    singleton_ref.acquired = true;
    return T { addr: get_txn_sender() };
  }
}

module Parent {
  resource T { cap: ParentCapability.T }

  public create(cap: ParentCapability.T) {
    move_to_sender<T>(T { cap });
  }

  // Once create has been called, Child.pick_up can only be called from here
  public pick_up(addr: address) {
    let t_ref = borrow_global<T>(addr);
    Child.pick_up(&t_ref.cap);
  }
}

module Child {
  public pick_up(cap: &ParentCapability.T) { ... }
}

```

**Comment by crabex** [comment]
@sblackshear:

It looks to be a very smart solution to my problem.
I have quite a few parent modules to authorize the access.
It should be very easy to improve your code to put a counter for the singleton.
Thanks a lot.

George Wu

**Comment by davidiw** [comment]
This looks resolved, please reopen if it hasn't been.
