### ISSUE TITLE
tower-grpc and Prost

### ISSUE THREAD

**Issue by uschen** [libra/libra#221]
## ❓ Questions and Help

Since PingCAP seemly moves towards tower-grpc and prost:

* https://github.com/pingcap/kvproto/blob/d288a78c7482b8abf254b97ec87fad3128f6c424/Cargo.toml#L17
* https://medium.com/@siddontang/use-tower-grpc-for-tikv-6109cf8c61
* https://github.com/tikv/tikv/issues/3951

wonder if libra considers to use pure rust implementation instead of c binding grpc?

**Comment by bmwill** [comment]
Yeah we're aware of PingCap heading towards using tower-grpc and prost over grpcio so its on our radar but we haven't taken any action to migrate ourselves yet. I personally would prefer a pure rust implementation (especially if we can drop the requirement for protoc to be installed on the system in order to build the project).

Thanks for bringing this up, maybe this will prompt us to investigate if it's worth the effort to switch sooner.

**Comment by carllerche** [comment]
Feel free to reach out to us in gitter as well. Happy to answer any questions re: tower-grpc 👍 http://gitter.im/tower-rs/tower

**Comment by bmwill** [comment]
@carllerche Thanks for the offer! I'll be sure to hit you up once we start taking a closer look at this 😄

**Comment by bmwill** [comment]
We've successfully completed migrating from grpcio to tonic as of last week!
