### ISSUE TITLE
[State sync] Check progress should be able to terminate pending state sync requests

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#2241]
Consider a scenario, in which a state sync request retrieved all the required chunks but failed in the `process_commit()` function.
The state sync request is going to remain pending. All the future invocations of `check_progress()` are not going to send new chunk requests because the DB is already updated. The system is thus stuck because consensus is waiting for a state sync request that is never going to get terminated.

One solution is to make sure that `check_progress()` can release the pending requests that are already satisfied.

**Comment by christinacelee** [comment]
I think currently the only way `process_commit` will fail is if `sync_state_with_local_storage` fails. In that case, `check_progress` will send new chunk requests (because the locally synced state is still outdated), and the whole flow will resume.

Feel free to re-open if there is another relevant edge case that is missing!
