### ISSUE TITLE
[Bug] Sequence number not well recovered

### ISSUE THREAD

**Issue by avysel** [libra/libra#235]
# 🐛 Bug

When recover account, sequence number are not well recovered. Then account is in inconsistent state.

## To reproduce

1. Create 2 accounts
2. Mine some Libra for account 0
3. Transfer Libra from account 0 to account 1
4. Query balances and sequences, it's OK. Sequence of account 0 is 1
5. Write accounts on disk
6. Quit then start again Libra
7. Recover account from previously created file
8. Display accounts list : KO, sequence number for account 0 is back to 0
9. Query sequence : OK, sequence of account 0 is 1
10. Transfer Libra from 0 to 1 : [ERROR] Failed to perform transaction: Transaction failed with vm status: Validation(SequenceNumberTooOld), please retry your transaction.

See example below :

```
libra% account list
No user accounts
libra% account create
>> Creating/retrieving next account from wallet
Created/retrieved account #0 address 99316e5aefc9b8ad915b02d91eb0b3c4dbb081021fc7ab319e559510ae6317ba
libra% account create
>> Creating/retrieving next account from wallet
Created/retrieved account #1 address 45627f7402f7df3f967b22fd6824440947584adac2f851638e955840adfdaf3a
libra% account mint 1 10
>> Minting coins
Mint request submitted
libra% account mint 0 10
>> Minting coins
Mint request submitted
libra% transfer 0 1 1
>> Transferring
Transaction submitted to validator
To query for transaction status, run: query txn_acc_seq 0 0 <fetch_events=true|false>
libra% account list
User account index: 0, address: 99316e5aefc9b8ad915b02d91eb0b3c4dbb081021fc7ab319e559510ae6317ba, sequence number: 1, status: Local
User account index: 1, address: 45627f7402f7df3f967b22fd6824440947584adac2f851638e955840adfdaf3a, sequence number: 0, status: Local
libra% account write wallet.txt
>> Saving Libra wallet mnemonic recovery seed to disk
Saved mnemonic seed to disk
libra% quit
```

Then

```
libra% account recover wallet.txt
>> Recovering Wallet
Wallet recovered and the first 2 child accounts were derived
#0 address 99316e5aefc9b8ad915b02d91eb0b3c4dbb081021fc7ab319e559510ae6317ba
#1 address 45627f7402f7df3f967b22fd6824440947584adac2f851638e955840adfdaf3a
libra% account list
User account index: 0, address: 99316e5aefc9b8ad915b02d91eb0b3c4dbb081021fc7ab319e559510ae6317ba, sequence number: 0, status: Local
User account index: 1, address: 45627f7402f7df3f967b22fd6824440947584adac2f851638e955840adfdaf3a, sequence number: 0, status: Local
libra% query sequence 0
>> Getting current sequence number
Sequence number is: 1
libra% transfer 0 1 1
>> Transferring
[ERROR] Failed to perform transaction: Transaction failed with vm status: Validation(SequenceNumberTooOld), please retry your transaction.
```

## Expected Behavior

After recovering, sequence number for account 0 should be 1 when typing "account list"

## System information

**Please complete the following information:**
- Libra master/737839b
- rustup 1.18.3 (435397f48 2019-05-22)
- Ubuntu 18.04

**Comment by xfyfb** [comment]
Thanks for the report! This is an expected behavior, not a bug. By default, client will only recover private/public key/address but not the sequence number. Because it has to sync with validator for the latest sequence number in its best effort. It becomes an issue if there are too many accounts to query. If you really want to sync sequence number during recovery, you can use -r(--sync) option of the client.

**Comment by avysel** [comment]
Thanks for your answer.

But I don't really understand.
When client starts, sequence number is going to be sync, but only after a random time. So, in my example, I just typed the "account list" too early ?
Is that what you mean ?

**Comment by xfyfb** [comment]
Well, sequence number is not an easy thing to keep sync in the world of asynchronousness. As mentioned, the sync feature of recovery/at start is turned off by default, but you can turn it on with -r(--sync). And there is no guarantee it will always succeed because the sync request can fail. 
There are currently couple of other ways to sync sequence number:
1. query the sequence number with reset=true
2. auto set to the latest from validator when SequenceNumberTooOld error happens.
The `account list` will just print everything local, no request to validator.

**Comment by avysel** [comment]
Alright, it's clear.
I understand better now, after trying the tips you gave me.

But it's a little confusing having two different values for the same data :)

Thanks a lot
