### ISSUE TITLE
client dev compile does not consider  output_file_path

### ISSUE THREAD

**Issue by nruppatel133** [libra/libra#2447]
### When compiling move modules/scripts on a local network one has following command documentation:

`compile | c <sender_account_address>|<sender_account_ref_id> <file_path> <module|script> [output_file_path (compile into tmp file by default)] Compile move program`

But when you want to use the last (optional) parameter "output_file_path" to specify your own file name, the standard temp file name (randomly generated) is still used.

In client/cli/src/client_proxy.rs in function compile_program the element at the 4th index of the array input parameter space_delim_strings would contain the custom "output_file_path" value, but it isn't considered.

pls fix thx.

**Comment by davidiw** [comment]
@sblackshear, if I recall correctly this was removed to support compilation of modules and their dependencies?

**Comment by sblackshear** [comment]
@runtian-zhou, would you mind taking a look at this?

**Comment by bob-wilson** [comment]
I can confirm this was broken. I've resolved it for now by removing the output_file_path argument. We've switched over to use the Move source language compiler now, and although it provides an option to specify an output directory, it may produce multiple output files in that directory. There's currently no way to specify a single output file. It was also hard to continue supporting an optional argument to the "dev compile" command because that command now ends with an arbitrary number of dependency arguments.
