### ISSUE TITLE
We may suggest to use blake2b instead of SHA256/512

### ISSUE THREAD

**Issue by hadv** [libra/libra#248]
We may suggest to use blake2b instead of SHA256/512 to boost up the performance.

https://coinguides.org/blake2b/

https://github.com/oconnor663/blake2_simd

**Comment by kchalkias** [comment]
Thanks for the recommendation @hadv. Actually Libra is not using sha256, but sha3-256, which is closer to blake2b in terms of speed, at least in software, because hardware implementations of sha3 are faster. Some of the design decisions were also based on the fact that sha3 is standardized, widely 
supported (i.e., from HSM vendors) and its sponge design allows for easier use as a XOF or MAC or salted hash function (i.e., SHAKE, KMAC etc).

**Comment by hadv** [comment]
@kchalkias Great to know this, thanks!
