### ISSUE TITLE
[Bug] Failed to perform transaction but transaction is sometimes successful

### ISSUE THREAD

**Issue by ipatka** [libra/libra#257]
# 🐛 Bug

In the [My First Transaction](https://developers.libra.org/docs/my-first-transaction) tutorial the transfer command resulted in an error but the transfer sometimes completes successfully anyway.

To report a security issue, please email security@libra.org.  -->

## To reproduce

** Code snippet to reproduce **
```
libra% account create
libra% account create
libra% account mint 0 110
libra% account mint 1 52
libra% transfer 0 1 10
```

** Stack trace/error message **
```
>> Transferring
[ERROR] Failed to perform transaction: Codec(WireError(UnexpectedWireType(WireTypeVarint)))
```

## Expected Behavior

I expected `transfer 0 1 10` to result in the following output

```
>> Transferring
Transaction submitted to validator
To query for transaction status, run: query txn_acc_seq 0 0 <fetch_events=true|false>
```

Or if the transaction failed I expect the balances to remain unchanged. However sometimes the error is shown but when I query the balances the transfer was successful.

## System information

**Please complete the following information:**
- Libra commit 0f65497beda6a2553eafe4d0ff40d797925eb29d
- macOS 10.14.4

## Additional context

Competing the tutorial in zsh

**Comment by bmwill** [comment]
Thanks for reporting this issue. This is due to some breaking changes that were introduced to master making the latest master incompatible with the currently deployed testnet. See [this post](https://community.libra.org/t/testnet-update-scheduled-for-july-10th-with-breaking-changes/1143) for more information on the change and when a new testnet will be deployed.
