### ISSUE TITLE
[Consensus] Return the height field to the block metadata transaction?

### ISSUE THREAD

**Issue by dmitri-perelman** [libra/libra#2616]
@msmouse is working on a feature, which would provide a proof for a timestamp of a transaction. In order to prove a timestamp of a transaction you want to show that this transaction is in between two metadata transactions, and in order to show that we need to demonstrate that two metadata transactions belong to consecutive blocks.
In order to show that metadata transactions belong to consecutive blocks we need block heights.
There are two ways to get block heights:
1. Use a `NewBlock` events issued by the metadata txns: events are numbered.
2. Add a `height` field to a metadata txn.

Consensus used to carry the height field, but at some point we removed it because we thought it's not in use. We could add it relatively easily and then put it in the metadata txns.
@zekun000, @aching thoughts?

**Comment by zekun000** [comment]
there's already a `height` field in `libra_system.BlockMetaData`. once we emit event, we can just piggyback this number in the event.

**Comment by msmouse** [comment]
@zekun000  (see discussion in #2338), #2389 is a pending PR to emit that event, and I thought it may be more straightforward if we include the field in the transaction so that we don't even need the event stream to prove timestamps for transactions.
(I also think it may make a little bit more sense to let height be part of the BlockMetadata transaction to a blockchain "user" who's (I don't know why) reading through our transaction stream.)

**Comment by dmitri-perelman** [comment]
To be honest I feel that having height being part of txn metadata is a cleaner solution than being an event (mostly because height is determined by consensus, so it makes sense for consensus to just set it directly).
However, the `NewBlockEvent` could still be useful for other things, (e.g., in case a subscriber wants to tail the metadata in order to calculate some stats about validator voting, or wants to know the timestamps of the last committed block).

**Comment by zekun000** [comment]
Personally I feel event is cleaner, also events serve as indexing so that we don't need to build another index for the metadata txns.

Reading arguments from txns is weird, it's like disassembling txns. If follow this logic, we can read from transactions for most data we want like proposer, votes, even the sent/received amount.

**Comment by msmouse** [comment]
I guess I'm still in the mind set where something to represent a "block" should exist. Without a first class Block data structure, I tend to think of the BlockMetadata to serve that purpose. But events work for me too. I will build the API around whichever way you guys decide to go.

**Comment by dmitri-perelman** [comment]
I agree with @msmouse on this one: we already include *some* metadata of every block in the BlockMetadata transactions, so it makes sense to add the height there as well.

**Comment by msmouse** [comment]
Looks like the consensus (by implementors) is to use the new block event stream (#2955), will proceed from there.
