### ISSUE TITLE
[Bug][VM] Error fetching module "GasSchedule" when running executor benchmark

### ISSUE THREAD

**Issue by ShuoWangNSL** [libra/libra#2622]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```bash
cargo run -p executor --bin bench
```

**Stack trace/error message**
```
I0218 22:56:52.907437 140238160856832 storage/libradb/src/lib.rs:173] Opened LibraDB at "/tmp/4747eda7bd6e61889a97d18e90fdbd7d/libradb/db/libradb" in 57 ms
C0218 22:56:52.909105 140238160856832 language/vm/vm-runtime/src/code_cache/module_cache.rs:263] [VM] Error fetching module with id ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000000, name: Identifier("GasSchedule") }
I0218 22:56:52.912696 140238160856832 executor/src/lib.rs:384] GENESIS transaction is committed.
I0218 22:57:13.056138 140238160856832 executor/src/benchmark.rs:241] Version: 500. execute time: 156 ms. commit time: 95 ms. TPS: 1982.
I0218 22:57:13.319050 140238160856832 executor/src/benchmark.rs:241] Version: 1000. execute time: 156 ms. commit time: 106 ms. TPS: 1901.
```

## Expected Behavior
GasSchedule Module should be successfully fetched. However, transactions still get executed after this error. It is not clear how the error of fetching GasSchedule module affects the execution of transactions.

## System information

**Please complete the following information:**
- 
master commit 68d60b8d1750173e3e1658af845ec2e03121ba76
- 
rustc 1.40.0 (73528e339 2019-12-16)
rustup nightly-2019-09-13 (default)
- 
Ubuntu 18.04

## Additional context

The error could also be seen in the commit message of commit c0dbab026dbddd51a6ea1630da0f0207abee8afb

**Comment by wqfish** [comment]
@tzakian can you check?

**Comment by tzakian** [comment]
Taking a look now

**Comment by tzakian** [comment]
Took a look at this and it is indeed a bug in the current implementation that was introduced in the past month or so. So thank you for finding it!

The bug arises from a chicken-and-egg problem in genesis -- we need the gas schedule to create an instance of the VM (at least at the moment), but we don't have that on-chain yet until the genesis transaction is published -- currently through the VM. The long-term resolution of this will be once WriteSet transactions are allowed in the VM. This in particular will allow the VM to apply the genesis transaction without trying to load the gas schedule from on-chain.

In the meantime, I'm looking at some short-term remediations of this -- I'll post an update here once the PR to fix this bug is up. 


Thanks again for reporting this!

**Comment by bob-wilson** [comment]
Has this been fixed yet?
