### ISSUE TITLE
[Bug] txn_executor panicked when running executor benchmark with small num-accounts

### ISSUE THREAD

**Issue by ShuoWangNSL** [libra/libra#2689]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```bash
cargo build  --release -p executor --bin bench
target/release/bench --num-accounts 50
```

**Stack trace/error message**
```
I0224 23:55:52.867383 140543670781696 storage/libradb/src/lib.rs:173] Opened LibraDB at "/tmp/87bfa1b8b997fb869ce19379b98b9a73/libradb/db/libradb" in 57 ms
C0224 23:55:52.868986 140543670781696 language/vm/vm-runtime/src/code_cache/module_cache.rs:263] [VM] Error fetching module with id ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000000, name: Identifier("GasSchedule") }
I0224 23:55:52.876006 140543670781696 executor/src/lib.rs:384] GENESIS transaction is committed.
I0224 23:55:52.908768 140543670781696 executor/src/benchmark.rs:271] Version: 50. execute time: 17 ms. commit time: 10 ms. TPS: 1789.
I0224 23:55:53.043362 140543670781696 executor/src/benchmark.rs:271] Version: 550. execute time: 68 ms. commit time: 65 ms. TPS: 3715.
thread 'txn_executor' panicked at 'assertion failed: `(left == right)`
  left: `1051`,
 right: `940`: Number of transactions in ledger info (1051) does not match number of transactions in accumulator (940).', executor/src/lib.rs:489:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'txn_generator' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1165:5
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:1165:5
```

## Expected Behavior

The benchmark works well when executing mint_transactions but has problems when executing transfer_transactions. When setting the num-accounts as a small value  instead of the default value 1000000, the mint part ends quickly and soon the problem happens. The benchmark for transfer_transactions is not working properly.
## System information

**Please complete the following information:**
- 
master commit 68d60b8d1750173e3e1658af845ec2e03121ba76
- 
rustc 1.40.0 (73528e339 2019-12-16)
rustup nightly-2019-09-13 (default)
- 
Ubuntu 18.04
## Additional context
Number of transactions in ledger info does not match number of transactions in accumulator.  But I haven't figured out how that happens.

**Comment by wqfish** [comment]
> Number of transactions in ledger info does not match number of transactions in accumulator.

For simplicity the benchmark wants all the generated transactions to be committed. I guess when the number of accounts are small, each account sends more transactions which cost more gas. When some account runs out of money, the transaction from that account fails and causes the assumption to fail. When there are a lot of accounts, each sends fewer transactions and it takes a lot longer for them to run out of money (since the benchmark picks accounts randomly).

One easy way to work around it might be to allocate more coins to each account. You can try the `init_account_balance` argument.

The benchmark is an initial prototype at the moment so it has limitations. We can think about improvements as we go.

**Comment by ShuoWangNSL** [comment]
Thanks very much for your reply.  It is indeed due to running out money.
