### ISSUE TITLE
Compiling libra on stable Rust

### ISSUE THREAD

**Issue by est31** [libra/libra#270]
There is a whitelist currently in [nightly_features.sh](https://github.com/libra/libra/blob/master/scripts/nightly_features.sh) of nightly features adopted in libra. I have made this issue (inspired by a similar issue in the rocket repo) to gauge which features will arrive on stable in the near term, which will take some time, and which never will, so that if libra wants to compile one day on stable Rust, it can do the needed changes.

## Likely arriving on stable soon

| Feature name | Most likely stable at |
| - | - |
| [async_await](https://github.com/rust-lang/rust/issues/50547) | 1.38 ([MVP at least](https://github.com/rust-lang/rust/issues/62149)) |
| [duration_float](https://github.com/rust-lang/rust/issues/54361) | 1.38 or 1.39 unless there is something stalling it ([PR](https://github.com/rust-lang/rust/pull/62756)) |
| [checked_duration_since](https://github.com/rust-lang/rust/issues/58402) | 1.39 most likely ([PR](https://github.com/rust-lang/rust/pull/62860)) |

* [repeat_generic_slice](https://github.com/rust-lang/rust/issues/48784): I guess this is a good candidate for filing a stabilization PR, there seems to be consensus for stabilizing it. Needs someone to push it past the finish line though.

## Only stable in the mid to long term

* [trait_alias](https://github.com/rust-lang/rust/issues/41517): there seem to be open questions still, I think it won't stabilize soon

* [specialization](https://github.com/rust-lang/rust/issues/31844): riddled with **SOUNDNESS HOLES** and likely to stay unstable for years to come, you should remove it.

* [slice_concat_ext](https://github.com/rust-lang/rust/issues/27747): similar to `checked_duration_since`.

* [crate_visibility_modifier](https://github.com/rust-lang/rust/issues/53120): It's a long thread with lots of back and forth and as there is no explicit agenda by any of the teams, I doubt they will stabilize it soon. It might even be removed in the future: I've heard concerns that it might be confusing with `crate::foo` paths.

* [drain_filter](https://github.com/rust-lang/rust/issues/43244): it seems the libs team didn't want to stabilize it, not sure whether they still hold that opinion: https://github.com/rust-lang/rust/issues/43244#issuecomment-376886108

* [exhaustive_patterns](https://github.com/rust-lang/rust/issues/51085) likely to stabilize together with never_type (see nmatsakis comment).

* [never_type](https://github.com/rust-lang/rust/issues/35121): this one was stabilized once and then they removed it again because of bugs. Not sure whether the bugs are all resolved, I guess they'll wait until stuff like `mem::uninitialized` has been removed from codebases so it'll take some time.

* **panic_info_message** (tracking issue is closed): not sure why used. You can just use the Display impl instead, it shouldn't be too hard.

## Likely never stable

* [box_syntax](https://github.com/rust-lang/rust/issues/49733) is going to be phased out, I'm not sure whether [box_patterns](https://github.com/rust-lang/rust/issues/29641) will be phased out as well but I definitely don't think they'll stabilize any time soon.

* **set_stdio**: never going to be stable, it's an internal feature.

* **test**: never going to be stable, as it's an internal crate. You can use the rustc-test crate instead: https://crates.io/crates/rustc-test

**Comment by bmwill** [comment]
This is great! Seriously thank you for taking the time to provide a clear breakdown (with references) to each nightly feature we're currently using. A number of us on the team have a goal of moving towards using stable Rust but due to a number of things (launching testnet for example) we didn't have the bandwidth for pushing on this as heavily as we'd like. I'm hoping that we'll have more time to push for this real soon.

So the next steps are:
1. Use the nightly_features.sh script in CI to prevent any additional features from being used.
2. Use this breakdown of each feature you've provided in order to eliminate our dependency on features which aren't on track for stabilization or won't be stabilized anytime soon.
3. Wait for remaining features to be stabilized and migrate to stable.

**Comment by bmwill** [comment]
If you've been following the most recent commits to the project you'll notice that @sunshowers and @huitseeker have done some great work pruning down that list down to only three nightly features. They are:
* async_await
* custom_test_frameworks
* set_stdio

The current plan is to do some engineering work to remove `set_stdio` and hopefully `custom_test_frameworks` so that when `async_await` graduates to the beta channel (maybe next month?) we can move from being on nightly to being on beta. Then once `async_await` graduates to stable we can move from beta to stable.

**Comment by sunshowers** [comment]
Only thing I'll add is that custom_test_frameworks is not a blocker since it is only used in test code. If we can't fix our use upstream we'll just work around it with a build.rs file and RUSTC_BOOTSTRAP.

**Comment by sunshowers** [comment]
It appears that stable async/await might not make it into 1.38: https://github.com/rust-lang/rust/pull/63209#issuecomment-520896750

Hopefully it'll be ready for 1.39!

**Comment by bmwill** [comment]
Update: As of #1072 libra no longer using nightly and instead uses the 1.39.0 beta toolchain. In 6 weeks when 1.39.0 is released to stable we should be able to move to stable.

**Comment by jaypalma** [comment]
usage: <command> <args>

Use the following commands:

account | a
  Account operations
query | q
  Query operations
transfer | transferb | t | tb
  <sender_account_address>|<sender_account_ref_id> <receiver_account_address>|<receiver_account_ref_id> <number_of_coins> [gas_unit_price (default=0)] [max_gas_amount (default 10000)] Suffix 'b' is for blocking.
  Transfer coins from account to another.
help | h
  Prints this help
quit | q!
  Exit this client


Please, input commands:

libra%

**Comment by est31** [comment]
Thanks @bmwill . I suppose it's mostly resolved then and is only a matter of waiting for the Rust 1.39 release.
