### ISSUE TITLE
[Bug] Mvir compilation error in official document on latest testnet

### ISSUE THREAD

**Issue by 5sWind** [libra/libra#3503]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
module MyModule {
  import 0x0.LibraCoin;

  // The identity function for coins: takes a LibraCoin.T as input and hands it back
  public id(c: LibraCoin.T): LibraCoin.T {
    return move(c);
  }
}
```

**Stack trace/error message**
```
error: 

   ┌── /Users/5swind/Downloads/Github/libra-move/my_module.mvir:2:3 ───
   │
 2 │   import 0x0.LibraCoin;
   │   ^^^^^^ Unexpected 'import'
   ·
 2 │   import 0x0.LibraCoin;
   │   ------ Expected 'fun'
   │

compilation failed
```

## Expected Behavior

Compile successfully.

## System information

**Please complete the following information:**
-  Libra latest testnet bb728128263ba54e311bf38cf1e573792e652096
-  rustc 1.41.1 (f3e1a954d 2020-02-24)
-  macOS

**Comment by bob-wilson** [comment]
This was fallout from PR #3425 that changes to use the Move source language instead of Move IR. We have just updated the "[Run Move Programs Locally](https://developers.libra.org/docs/run-move-locally)" section of the Libra documentation to translate the sample code to the Move source language and make other changes to the step-by-step instructions that accompany the examples. It should work now if you follow the updated documentation.
