### ISSUE TITLE
[Bug][security] CVE-2015-5237: Integer overflow in serialization

### ISSUE THREAD

**Issue by EvertonMelo** [libra/libra#374]
# 🐛 Bug security:

# "CVE-2015-5237: Integer overflow in serialization"

https://github.com/libra/libra/blob/master/language/e2e_tests/Cargo.toml#L25

because the dependency recommendation is very outdated: 

Required: protobuf = 2.7; ( add by https://github.com/libra/libra/commit/80140c9b8eec7f51d9a6147a45b29598647471cd#diff-80398c5faae3c069e4e6aa2ed11b28c0 ) 

 
The version is so old that it is no longer kept in the official repository: 
https://github.com/protocolbuffers/protobuf/releases 

the version protobuf v2.6.1 

https://github.com/protocolbuffers/protobuf/releases/tag/v2.6.1 

jumb the version v3.0.0 

https://github.com/protocolbuffers/protobuf/releases/tag/v3.0.0-alpha-1

    
    Version 2.7 is not supported.

another interesting point, The protobuf has antive support for: java, python, obj-c, js, ruby,  GO, php, dart.

https://github.com/protocolbuffers/protobuf/blob/master/README.md

but v3.0.x has package only: java, c++ and source code.
I found no evidence that protobuf compilation is required to use libra. 
I soon conclude that these same packages are used ( c++ or java ) 
This leads me to failure:

CVE-2015-5237: Integer overflow in serialization

## Sumary: 

It was discovered that the protobuf library and code generated by the
protobuf compiler store size information in an int variable, which may
truncate size values on 64-bit architectures, leading to a heap-based
buffer overflow.

more details:
https://github.com/protocolbuffers/protobuf/issues/760 
https://bugzilla.redhat.com/show_bug.cgi?id=1256426

according to the severity described:
## CVE-2015-5237: Integer overflow in protobuf serialization (currently minor)

This is currently not intended to be addressed upstream, which is a bit
disappointing.  It's true that this issue does not have much exposure
right now, but in a couple of years, the message sizes involved will not
seem so gigantic anymore.  And as explained in the bug report, fixing
this will be difficult because it involves updating generated code; it
won't be a simple library update.
font: https://www.openwall.com/lists/oss-security/2015/08/27/2 

## all versions prior to 3.4 < are vulnerable 

https://nvd.nist.gov/vuln/detail/CVE-2015-5237
please use a protobuf greater than v3.4 >

[To report a security issue, 
please email security@libra.org:](https://github.com/libra/libra/security/policy)
**submitted 3 business days ago** 
until now, nothing.

# Your code goes here

## Expected fixed

please use a protobuf greater than v3.4 >

## System information

**Please complete the following information:**
Libra Version: 0.1.0

Rust Version: 1.35
OS: debian 9.x

**Comment by jansegre** [comment]
`Cargo.toml` installs packages from [crates.io](https://crates.io/). The highlighted dependency is [this package](https://crates.io/crates/protobuf). Which was the [latest version](https://github.com/stepancheg/rust-protobuf/releases) at the time that commit was made. According to the [project's readme](https://github.com/stepancheg/rust-protobuf/) both Protbuf 2 and 3 are supported, but the implementation is made from scratch, so it has no relation with google's C++/Java implementations. I don't see how

**Comment by kchalkias** [comment]
@EvertonMelo, note that Rust's protobuf versioning is not aligned with the [official protobuf github](https://github.com/protocolbuffers/protobuf) version number. As @wqfish noticed, the rust protobuf crate is linked to [this commit](https://github.com/protocolbuffers/protobuf/tree/b5fbb742af122b565925987e65c08957739976a7) which is official protobuf 3.5.2.

**Comment by EvertonMelo** [comment]
guys.
please ready the doc FIRST. 

[3. Install **Dependencies**:
./scripts/dev_setup.sh](https://developers.libra.org/)

https://github.com/libra/libra/blob/master/scripts/dev_setup.sh#L118 

Let's be reasonable.

Please read the documentation before commenting.

If in doubt refer to the documentation and source code.

Understanding and communication is easier.

**Comment by jansegre** [comment]
@kchalkias

The Rust package isn't even linked to the official protobuf lib, the git submodule is there simply to reuse tests and protos.

@EvertonMelo 

I think it is reasonable to worry about this kind of issue. It's also reasonable to about the validity of any proposed solution. I'll completely agree that communication is essential.

In this case, if the version at https://github.com/libra/libra/blob/master/language/e2e_tests/Cargo.toml#L25 were to be set to anything greater than `2.8` (at the time of this comment), cargo will not be able to find the package and the project will simply fail to build. So that is not a valid solution. Testing that should be simple enough.

I want to clarify why this is the case. It certainly isn't obvious, and I apologize if I made it seem so.

Protobuf is not a simple piece of dependency that merely exists as a monolith. It has several components: the protocol files (`.proto` files), which describe protocols/messages; the compiler (`protoc`), which takes protocols as input and generates code to serialize/deserialize messages; and usually (because some compilers are able to generate code that has no external runtime) the runtime (`protobuf`), which the generated code uses to support in operations common to all serializers/deserializers. Furthermore, the compiler has a plugin mechanism to allow generators for any language to reuse the parsing/validation of protocol files and such.

The official implementation that Google offers has all of these pieces in the same repository for most of the officially supported languages (only Go and Dart are in separate repositories). But Rust is not officially supported, the Rust community has implemented their own solutions, the most prominent one by @stepancheg which is the package that will installed from that entry in `Cargo.toml`.

Now, about the CVE-2015-5237, it affects `cpe:2.3:a:google:protobuf:*:*:*:*:*:*:*:*` (up to excluding 3.4.0), while that is a bit broad it refers to this project: https://github.com/protocolbuffers/protobuf which, disregarding anything more specific to the issue itself, could at most affect the libra project on two occasions:

- Through the git submodule of the Rust implementation which is referred in the `Cargo.toml`, but as @kchalkias pointed out, the submodule references the protobuf project at the 3.5.2 version;
- Or at the location you pointed out (https://github.com/libra/libra/blob/master/scripts/dev_setup.sh#L118) (which was not mentioned before, and I had not seen, but since it is `protoc` it doesn't really better for other reasons, but considering it just for the sake of argument) which will install the protobuf compile (`protoc`, not the runtime) at version `3.8.0` (https://github.com/libra/libra/blob/master/scripts/dev_setup.sh#L118)

I think the effort to find vulnerabilities will always be appreciated. But in this case, this is not one that affects this project.

**Comment by EvertonMelo** [comment]
bug sent to: security@libra.org ignored for more than 1 month.

closed out of disinterest.
