### ISSUE TITLE
[Bug]There are potential security issues with Move Libra.register_currency 

### ISSUE THREAD

**Issue by jolestar** [libra/libra#3820]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
public fun register_currency<CoinType>(
        to_lbr_exchange_rate: FixedPoint32::T,
        is_synthetic: bool,
        scaling_factor: u64,
        fractional_part: u64,
        currency_code: vector<u8>,
    ) acquires CurrencyRegistrationCapability {
        // And only callable by the designated currency address.
        Transaction::assert(Association::has_privilege<AddCurrency>(Transaction::sender()), 8);

```

Anyone can write a script and call register_currency, and pass any CoinType as CoinType parameter. The only limit is  Association::has_privilege check.

I think security should be ensured through the mechanisms of builtin Move language, not through user permissions. Because if user privileges are compromised, there will be serious consequences.

For the example of move_check/examples/multi_pool_money_market_token.move: 

``` rust
module Token {
    use 0x0::Transaction;

    resource struct Coin<AssetType: copyable> {
        type: AssetType,
        value: u64,
    }

    // control the minting/creation in the defining module of `ATy`
    public fun create<ATy: copyable>(type: ATy, value: u64): Coin<ATy> {
        Coin { type, value }
    }
```

The `create` function requires an instance of the Assert type, not just AssertType. So, only the module that defines AssetType can invoke the `create` function. 

So, I think register_currency should also requires an instance of the CoinType.

**Comment by tzakian** [comment]
Hi there Jolestar,

Indeed the registration of a type as a currency on-chain is predicated on the caller to `register_currency` having the appropriate privileges granted to it by the association. Additionally, the granting, validity, and revocation of these privileges are enforced fully using the semantics of Move--privileges are represented as certified resources published under the account, and can be added/removed by the root association account using logic written in Move.

However, I don't necessarily see how adding the extra requirement that a witness of the `CoinType` type be passed-in in order to register a currency provides additional protections over what currently exist in this function.  I would be very interested in examples of any particular attacks that you are thinking of that I am not seeing, and that would be prevented with such an approach. 

Particularly, in my understanding of your proposal there are a couple parts I would love some clarification and/or insight on:
1. The creation of a value of the `CoinType` type would need to be permissioned in some manner, and would therefore need to rely on similar account-level checks at some point in order to determine whether it can create a witness of the given type. Of particular interest here is if there's a way of structuring permissions to line-up with Move's semantics around `move_to_sender` in order to maintain the singleton address for currency info while not relying on account-level checks in the process. However, at least at the moment I am not seeing how this can be done.
2.  Guarding a function by taking in a witness of the assertion doesn't provide any guarantees in a generic context as far as I can tell. In particular, nothing prevents someone from passing a `u64`, `address`, or other primitive (or unrestricted) copyable type in for the `type` parameter in the `create` function in your example (see functional test in [1]). I'm unsure how this could be guarded against in your proposed solution.

Thanks, and looking forward to hearing more!

[1] Example functional test instantiating the code with unrestricted
    primitive types:

```rust
// Simplified `Token` module taken from `move_check/examples/multi_pool_money_market_token.move`
module Token {
    use 0x0::Transaction;

    resource struct Coin<AssetType: copyable> {
        type: AssetType,
        value: u64,
    }

    // control the minting/creation in the defining module of `ATy`
    public fun create<ATy: copyable>(type: ATy, value: u64): Coin<ATy> {
        Coin { type, value }
    }

    public fun destroy_zero<ATy: copyable>(coin: Coin<ATy>) {
        let Coin { value, type: _ } = coin;
        Transaction::assert(value == 0, 11)
    }

}

//! new-transaction
script {
    use {{default}}::Token;
    use 0x0::Vector;
    fun main() {
        // Create tokens of arbitrary types use 0 so we can destroy them easily
        let token_u64 = Token::create<u64>(0, 0);
        let token_address = Token::create<address>(0xDEADBEEF, 0);
        let token_vec_u8 = Token::create<vector<u8>>(x"CAFE", 0);
        let token_vec_address = Token::create<vector<address>>(Vector::singleton(0xCAFE), 0);
        Token::destroy_zero<u64>(token_u64);
        Token::destroy_zero<address>(token_address);
        Token::destroy_zero<vector<u8>>(token_vec_u8);
        Token::destroy_zero<vector<address>>(token_vec_address);
    }
}
```

**Comment by jolestar** [comment]
Hi @tzakian 

In the example, if the Token issuer use u64 as coin type to issue a new Token, it represents that the issuer relinquished control of the Token, Or may Move can limit CoinType must be a struct?

But if the issuer uses a custom struct as CoinType,  they can write a custom strategy to limit CoinType usage.

For example, if the association grant  AddCurrency privilege to user Alice, let him issue a new Token AToken. But Alice becomes evil，or lost his key, he can try to register LBR and mint LBR.

[1] Example functional test abuse privilege, this test may break by the PR #3993 witch merged today, but I do not think it is the right approach to fix this. :

```rust
// Test c
//! account: vivian, 1000000, 0, validator
//! account: alice, 0LBR


// Apply privilege by alice
//! sender: alice
script {
use 0x0::Association;
use 0x0::Libra;
fun main() {
    Association::apply_for_association();
    Association::apply_for_privilege<Libra::AddCurrency>();
}
}

// Grant privilege to alice
//! new-transaction
//! sender: association
script {
use 0x0::Association;
use 0x0::Libra;
fun main() {
    Association::grant_association_address({{alice}});
    Association::grant_privilege<Libra::AddCurrency>({{alice}});
}
}
// check: EXECUTED

// Check privilege
//! new-transaction
//! sender: alice
script {
use 0x0::Association;
use 0x0::Transaction;
use 0x0::Libra;
fun main() {
    Transaction::assert(Association::has_privilege<Libra::AddCurrency>(Transaction::sender()), 8);
}
}

// check: EXECUTED

//! block-prologue
//! proposer: vivian
//! block-time: 100000000

// Register LBR again with alice
//! new-transaction
//! sender: alice
script {
use 0x0::Libra;
use 0x0::LBR;
use 0x0::FixedPoint32;
fun main() {

    Libra::register_currency<LBR::T>(
                FixedPoint32::create_from_rational(1, 1), // exchange rate to LBR
                true,    // is_synthetic
                1000000, // scaling_factor = 10^6
                1000,    // fractional_part = 10^3
                x"4C4252" // UTF8-encoded "LBR" as a hex string
            );
}
}

// check: EXECUTED


// Self mint LBR
//! new-transaction
//! sender: alice
script {
use 0x0::Libra;
use 0x0::LBR;
use 0x0::LibraAccount;
use 0x0::Transaction;
fun main() {
    let token = Libra::mint<LBR::T>(10000);
    LibraAccount::deposit_to_sender(token);
    Transaction::assert(LibraAccount::balance<LBR::T>(Transaction::sender()) == 10000, 1111)
}
}

// check: EXECUTED
```

**Comment by tzakian** [comment]
Hi Jolestar,
> For example, if the association grant AddCurrency privilege to user
> Alice, let him issue a new Token AToken.

This behavior is not possible in the system as it stands today unless `alice` is the account in charge of currencies on-chain. There is a restriction that the calling address for currency registration is a specific address in order for the registration of `Tok` to be successful in registering it as a recognized currency on-chain (viz.: `Libra::is_currency<T>()`). In particular the scenario that you describe can't happen since:
* If `alice` (where `alice`'s address is `!= Libra::currency_addr()`) did have an `AddCurrency` privilege, they could not successfully add any additional tokens `Tok` as a recognized currency. Particularly, the `CurrencyInfo<Tok>` resource wouldn't be published under the singleton address `Libra::currency_addr()` but under alice's account (which is `!= Libra::currency_addr()`) and therefore `Tok` wouldn't be considered a currency in the system by the currency module since `Libra::is_currency<T>()`  requires this. And;
* The root association account would not grant an `AddCurrency` privilege if one was already granted to the account at address `Libra::currency_addr()`.


> But if the issuer uses a custom struct as CoinType, they can write a
> custom strategy to limit CoinType usage.

With the way currency registration works--that it needs to be a specific address registering the currency--I still fail to see how having custom permissioning strategies in a module per coin type buys any additional security guarantees. In particular, in Libra, there can only be _one_ account that can register currencies in the system---the account at address `Libra::currency_addr()`---and therefore there is no real concept of "issuers" in the system:
* The `CurrencyInfo<CoinType>` resource is required to be at a specific address; `Libra::currency_addr()`.
* We only have `move_to_sende`r semantics outside of the creation of an account, therefore the caller of any valid registration of a token as a currency would need to be sent from that specific account address--the account at address `Libra::currency_addr()`.
* In the case of compromise, adding value-level restrictions and permissions in the module doesn't buy any additional guarantees as far as I can tell, because all of the modules defining currencies would need to have checks that would need to be account address or permission-based, in which case we would have the same checks and guards against this type of compromise as we do now. I.e. the module checks would all need to be of a similar form:
  ```rust
  module MyToken {
      resource struct T {}
      public fun grant_token(): T {
          Transaction::assert(Transaction::sender() == Libra::currency_addr(), 0);
          T {}
      }
  }
  ```

**Comment by jolestar** [comment]
Hi, tzakian.

I got it. The Currency on Libra is different with Erc20 Token on Ethereum. I want to find an Erc20 Token standard solution on Libra. Do you have some suggestions?

**Comment by tzakian** [comment]
Hi Jolestar,

If you wanted to implement ERC-20, I don't have any suggestions per-se, but I
mocked up a module over the weekend that I'm fairly certain would allow you to define an
ERC-20-like interface. (Not sure if this code is 100% correct, so
make no guarantees, but I think it conveys the general idea of how you
could do this).

```rust
module MyToken {
    use 0x0::Transaction;
    use 0x0::Signer;

    resource struct Token<Tok> {
        amount: u64,
    }

    resource struct RegisteredTokenProvider<Token> {
        token_provider_addr: address,
    }

    // This is held under the registered_address
    resource struct TokenInfo<Token> {
        witness: Token,
        market_cap: u128,
        scaling_factor: u64,
        decimals: u64,
        // other info here...
    }

    resource struct TokenCreationCap<Token> {}

    public fun register_token_provider<Token>(singleton_account: &signer, token_provider_addr: address) {
        Transaction::assert(Signer::address_of(singleton_account) == singleton_addr(), 0);
        move_to(singleton_account, RegisteredTokenProvider<Token> { token_provider_addr })
    }

    public fun register_token<Token>(
        token_provider_account: &signer,
        witness: Token,
        scaling_factor: u64,
        decimals: u64
    ): TokenCreationCap<Token> acquires RegisteredTokenProvider {
        let registered_token_provider_addr = borrow_global<RegisteredTokenProvider<Token>>(singleton_addr()).token_provider_addr;
        Transaction::assert(Signer::address_of(token_provider_account) == registered_token_provider_addr, 1);
        move_to(token_provider_account, TokenInfo<Token>{
            witness,
            market_cap: 0,
            scaling_factor,
            decimals,
        });
        TokenCreationCap<Token>{}
    }

    public fun is_token<Token>(): bool
    acquires RegisteredTokenProvider {
        if (exists<RegisteredTokenProvider<Token>>(singleton_addr())) {
            let token_addr = borrow_global<RegisteredTokenProvider<Token>>(singleton_addr()).token_provider_addr;
            exists<TokenInfo<Token>>(token_addr)
        } else {
            false
        }
    }

    public fun make_tokens<Tok>(_cap: &TokenCreationCap<Tok>, amount: u64): Token<Tok>
    acquires TokenInfo, RegisteredTokenProvider {
        let registered_addr = borrow_global<RegisteredTokenProvider<Tok>>(singleton_addr()).token_provider_addr;
        let info = borrow_global_mut<TokenInfo<Tok>>(registered_addr);
        info.market_cap = info.market_cap + (amount as u128);
        Token<Tok> { amount }
    }

    public fun singleton_addr(): address {
        // Could be any address. But address owner is the only one that has
        // the ability to register token providers. Use 0xA550C18 since we
        // can send from that specific address in the functional tests.
        0xA550C18
    }
}
```

Then issuers could write their tokens something like this:
```rust
module BobToken {
    use 0x0::Transaction;
    use 0x0::Signer;
    use 0x0::MyToken::{Self, Token, TokenCreationCap};

    resource struct T {}
    resource struct Creator {
        cap: TokenCreationCap<T>
    }

    public fun register(sender: &signer) {
        Transaction::assert(Signer::address_of(sender) == 0xB0B, 0);
        let cap = MyToken::register_token<T>(sender, T{}, 100, 10);
        move_to(sender, Creator{ cap })
    }

    public fun create(sender: &signer, amount: u64): Token<T>
    acquires Creator {
        Transaction::assert(Signer::address_of(sender) == 0xB0B, 0);
        // put module-specific logic here
        MyToken::make_tokens<T>(
            &borrow_global<Creator>(0xB0B).cap,
            amount
        )
    }
}
```
This would require a designated account to register the token provider's
address on chain (e.g. `0xA550C18` would need to
`register_token_provider<BobToken::T>(0xB0B)` before the `BobToken::T`
could be registered.

**Comment by jolestar** [comment]
if I want to omit the singleton_addr and allow anyone as a token provider to register a token. How can I do it? I can not find a way to save the token provider info. @tzakian

**Comment by jolestar** [comment]
I try to implement a reflection mechanism to do this, get the TokenType module address by TokenType at #4468, but do not be support.

**Comment by jolestar** [comment]
Another solution is to use a Map to keep TokenType -> TokenProviderAddress mapping. But we don't currently have a map.

**Comment by tzakian** [comment]
The reason you need the `singleton_addr` is if you want to implement `is_token<Token>`, and if you want to be able to get information about the coin only using type-level information. If you want to allow arbitrary tokens to be created and used by anyone, but where they control the creation of those tokens, you should be able to modify it slightly, and do something along the lines of:
```rust
module OpenToken {
    use 0x0::Transaction;
    use 0x0::Signer;

    resource struct Token<Tok> {
        amount: u64,
        provider_addr: address,
    }

    // This is held under the registered_address
    resource struct TokenInfo<Token> {
        witness: Token,
        market_cap: u128,
        scaling_factor: u64,
        decimals: u64,
        // other info here...
    }

    resource struct TokenCreationCap<Token> {
        token_provider_addr: address
   }

    public fun register_token<Token>(
        token_provider_account: &signer,
        witness: Token,
        scaling_factor: u64,
        decimals: u64
    ): TokenCreationCap<Token> acquires RegisteredTokenProvider {
       let token_provider_addr = Signer::address_of(token_provider_account);
        move_to(token_provider_account, TokenInfo<Token>{
            witness,
            market_cap: 0,
            scaling_factor,
            decimals,
        });
        TokenCreationCap<Token>{ token_provider_addr }
    }

    public fun make_tokens<Tok>(cap: &TokenCreationCap<Tok>, amount: u64): Token<Tok>
    acquires TokenInfo {
        let info = borrow_global_mut<TokenInfo<Tok>>(cap.token_provider_addr);
        info.market_cap = info.market_cap + (amount as u128);
        Token<Tok> { amount, provider: cap.token_provider_addr  }
    }

   public fun scaling_factor<Tok>(tok: &Token<Tok>): u64 {
       let info= borrow_global<TokenInfo<Tok>>(tok.provider);
       info.scaling_factor
   }
}
```

I haven't tested this so there may be issues, but I think it gives the general idea :) 

Also, I think we've covered and resolved the original issue at this point so I'm going to close this issue.

**Comment by jolestar** [comment]
@tzakian  Thanks.  

>  resource struct Token<Tok> {
        amount: u64,
        provider_addr: address,
    }

Keep provider_addr in Token resource is a method, but it is redundancy and waste user's state space. Is there a more good method?
