### ISSUE TITLE
[Feature Request]Stdlib LCS support from_bytes

### ISSUE THREAD

**Issue by jolestar** [libra/libra#5109]
# 🚀 Feature Request

## Motivation

LCS Module currently only supports to_bytes, serialize MoveValue to bytes, do not supports from_bytes, deserialize MoveValue from bytes. 

expect a Native method:

```move
native public fun from_bytes<MoveValue>(v: &vector<u8>): MoveValue;
```

Usage case:

Serialize struct to vector<u8> as script argument and deserialize to Struct in Move. 
Such as LibraVMConfig.publishing_option can be a Struct in Move, the LibraVM's is_allowed_script,is_allowed_module check logic can also move to Stdlib(txn prologue).

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

**Comment by bob-wilson** [comment]
@matbd have we considered this?

**Comment by sblackshear** [comment]
This API is not safe--`MoveValue` could be resource (e.g., a `Coin`). It's very important for Move's security model that `Pack` is the only way to create a type. So it is fine for us to support serialization of (references to) Move values in Move bytecode, but we cannot support deserialization. Even `native public fun from_bytes<MoveValue: copyable>(v: &vector<u8>): MoveValue;` would not be safe because it could create a sensitive `struct` type.

**Comment by jolestar** [comment]
@sblackshear If LCS::from_bytes is not safe, what about supports pass Struct as script's argument as I mention at #4264 ?

**Comment by sblackshear** [comment]
Good question! It is also not safe to allow `struct`s as script arguments (just like it is not safe to allow resources as script arguments). I will also comment on the other issue.
