### ISSUE TITLE
[libra-channel] garbage collect disconnected peers from channels

### ISSUE THREAD

**Issue by phlip9** [libra/libra#5543]
[`libra-channel`](https://github.com/libra/libra/blob/master/common/channel/src/libra_channel.rs) never removes keys (`(PeerId, ProtocolId)` in this case) from its `PerKeyQueue`. this works fine for the validator network, where we have a bounded set of peers that rarely changes; however, this does not work for servicing public clients, where we can have large and frequent connection churn.

1. the simplest approach would be to completely remove a key from the `PerKeyQueue` if we pop a message and the queue is empty. however, this would lead to thrashing as we would frequently add+allocate then remove+deallocate the queue.

2. periodically garbage collect on a timer, i.e.,`Receiver::poll_next()` internally polls a timer and removes empty queues on trigger. similar thrashing issue, just less frequent. adds some tail latency from locking the `PerKeyQueue` while iterating through the keys.

3. hook into LostPeer lifecycle directly. add a `remove_key` API to `Sender` (also `Receiver`?). this approach seems the most efficient, but introduces a bit of boilerplate and error-prone ceremony to application protocols, who might forget to clear lost peers. also seems pretty racy; hard to get right.

option (2) seems like a good tradeoff and is completely transparent in the current API.

@gregnazario @davidiw any thoughts?

**Comment by davidiw** [comment]
Hmm.... could we make an explicit callback or trait that implements a GC? And then we can implement different GCs for where ever they are used? When used for networking, the GC could be to simply kill the queue when the peer has disconnected. So you'd have a struct that implements a trait for doing just that. I don't think we use Libra-channel otherwise, but this would keep the code in libra-channel still crate agnostic.

I think your proposal #2 could also be another implementation within this space.

Do we have an estimate of what it costs for each peer across the system? Like the null state space for a single (fullnode) node across all the queues in the system.

**Comment by gregnazario** [comment]
Yeah, I agree.  Let's look at we can make a trait that implements GC, because we could have multiple GC strategies, such as leaving a threshold on the number of queues we let sit and then provide an eviction policy, such as least recently used.  It would be hard to know without real traffic what would be best, because if the messages from a peer come at a time > the poll timer, it's possible we keep creating the queue over and over.

#2 seems like the path to go forward, but generalizing for expansion could be helpful.

Btw @davidiw, we seem to have a bunch of generalized code in the common crates that's only used for networking, and as much as I'd like to say that they're generic, they seem sometimes a little specific (backoff comes to mind).  Should we push to use these multiple places, rename them so that they're maybe more pointed towards networking, or just let them be?

**Comment by phlip9** [comment]
Closed by #5968
