### ISSUE TITLE
Cluster discovery seem to break if first connected peer give list of wrong IPs

### ISSUE THREAD

**Issue by andll** [libra/libra#587]
We had situation in cluster test, when it partitioned into 2 independent sub-clusters with 86 and 14 machines. Machines in those sub-clusters could connect to each other, but did not see machines outside of sub-cluster.

Validators in smaller (14 machines) cluster had correct seed peer config file, pointing to machines in bigger cluster, however they did not try to connect to them. Instead they assumed, for some reason, wrong IP addresses for those seed peers.

I restarted one machine in smaller sub-cluster, but it still was not able to reconnect to bigger sub-cluster. It seems that one of other machines in smaller group sent it wrong IP addresses before this machine tried using seed peers.

Once I restarted all machines in small sub-cluster simultaneously, they was able to recover and reconnect with everyone else.

cc @0-o-0

**Comment by bothra90** [comment]
We now know that when 1 machine in the smaller cluster (let's call it node A) was restarted it didn't join the larger cluster because of the following sequence of events:
1. Node A restarted (with the new seed address)
2. Nodes in the smaller cluster notice that they've lost connection with A and try to reconnect
3. Some node (let's call it node B) in the smaller cluster connects to A and sends it a discovery note signed by the seed peer, but for the older address.
4. Node A updates the seed peer address from the one it started with (in configuration) to the one it received from node B. It does so because the seed peer address it starts off with does not have an associated timestamp.

In addition, we know that the partition happened in the first place because the nodes started in a random order. Nodes which restarted before the seed node will discover and connect to each other, but will not be able to discover nodes which restarted after the seed node restarted.

There's multiple things we need to do to fix the overall problem:
1. Attach a timestamp to the configuration and ignore seed peer addresses older than that timestamp.
2. Persist peer information - this way, after the seed node restarts, it will be able to introduce nodes which restarted before it to the nodes which restart after it.
3. Have multiple seed nodes.
