### ISSUE TITLE
[Feature Request] Include move_to function

### ISSUE THREAD

**Issue by PJUllrich** [libra/libra#61]
# 🚀 Feature Request

The `Move` language includes `move_from()` and `move_to_sender()` functions, however it does not include a `move_to()` function in which a recipient address can be specified. This function is however included already in the [vm](https://github.com/libra/libra/blob/5e034dde19a5320d7e2bdc9da25114e816b4454d/language/vm/src/file_format_common.rs#L141). Please include this function in the `stdlib`:

```
move_to<t: StructName>(recipient: address, t: struct)
```

## Motivation

This function is necessary in order to send a resource to another address than the sender's. A use case could be a product to which the ownership rights can be sold to another person. In this case, the rights need to be `moved_from` the **sender's address** and `moved_to` the **recipient's address**.

## Pitch

**Describe the solution you'd like**
Integrate the [vm](https://github.com/libra/libra/blob/5e034dde19a5320d7e2bdc9da25114e816b4454d/language/vm/src/file_format_common.rs#L141) function `MOVE_TO` into the [Builtin syntax](https://github.com/libra/libra/blob/5e034dde19a5320d7e2bdc9da25114e816b4454d/language/compiler/src/parser/syntax.lalrpop#L203).

**Describe alternatives you've considered**
I'm not aware of how to solve the problem from my motivation otherwise. If that's possible, please advise.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))
I would try, yes. 

### Example Code of my Problem
```
module Counter {
    resource T {
        counter: u64
    }

    public create() {
        let t: R#Self.T;

        t = T {
            counter: 0
        };

        return move(t);
    }

    public increment(counter_address: address) {
        let t: R#Self.T;
        let t_new: R#Self.T;
        let increment: u64;

        T { counter } = move(counter_address);
        increment = 1;

        t_new = T {
            counter: move(counter) + copy(increment)
        };

        // The counter should stay at the same address
        move_to<T>(counter_address, t_new);

        return;
    }
}
```

**Comment by sblackshear** [comment]
Good question/suggestion! The restrictive nature of `MoveToSender` is intentional, and it's not in our plans to support a more permissive `MoveTo(address)`. We discuss the reasoning for this in more detail in this Discourse [post](https://community.libra.org/t/move-to-sender-but-with-a-specified-address/201/2), but I'll briefly summarize here + suggest a design pattern for what you are trying to implement.

### Why Move implements MoveToSender instead of MoveTo(address)
Move does not allow you to move a resource to an address other than the sender’s. The reason for this is that publishing a resource under your account is a privileged operation. Letting someone else publish a resource under your account would be like letting someone else install an app on your phone. Restricting this privilege to the transaction sender ensures that Libra users have control over the content of their own accounts. No one should be able to clutter account storage with resources the owner doesn’t want.

### Implementing the counter example

```
module Counter {
    resource T {
        counter: u64
    }

    // lets anyone publish a Counter.T under their account
    public create() {
        let t: R#Self.T;

        t = T {
            counter: 0
        };
        move_to_sender<T>(move(t));

        return;
    }

    public increment(counter_address: address) {
        let t_ref: &mut R#Self.T;
        let counter_ref: &mut u64;

        // acquire a mutable reference to the T at counter_address
        t_ref = borrow_global<T>(move(counter_address));
        counter_ref = &mut move(t_ref).counter;
        // increment the counter by mutating the reference
        *move(counter_ref) = *copy(counter_ref) + 1;

        return;
    }
}
```

**Comment by PJUllrich** [comment]
Thanks, that clears it up. I agree with your decision on keeping the `move_*` functionality limited. I have some questions regarding `resources`, but I'll open another issue for that. Thanks however for your answer!

**Comment by aihuawu** [comment]
If this function is however included already in the vm, then people can do it in bytecode level.
Am I right? So in order to totally get rid of this functionality, you have to remove this function
in the virtual machine.

**Comment by aihuawu** [comment]
Without move_to, you are unable to send an asset to someone unless she has the asset. 
In the above code, you can only modify other people's assets, you can't create the assets.

This pattern is totally different from what etherum ERC20 does.
What's the best pattern to transfer assets to other people?
