### ISSUE TITLE
[logging] Consider putting JSON of data in message field

### ISSUE THREAD

**Issue by gregnazario** [libra/libra#6200]
At request of @davidiw 

### Current behavior
Lack of a message means no message
```
info!(key=value)
=> {"data":{"key":"value"}}
```
### Requested behavior
Lack of a message means put JSON of data in the message field
```
info!(key=value)
=> {"data":{"key":"value"}, "message":"{"key":value"}"}
```

**Comment by bmwill** [comment]
I'm not quite sure what this is asking for. @davidiw could you elaborate a bit more?

**Comment by gregnazario** [comment]
> I'm not quite sure what this is asking for. @davidiw could you elaborate a bit more?

I've updated with what david and I talked about

**Comment by bmwill** [comment]
I'm not quite sure I understand how this is useful, other than doubling the number of bytes logged

**Comment by davidiw** [comment]
so when I hop into kibana, the default log line is empty. That makes my logs useless without hitting the carrot so that you can see more information in it.

**Comment by bmwill** [comment]
I would suggest you just add a message to your log lines then :P

**Comment by davidiw** [comment]
my log lines are the message, it would literally be duplicating itself

**Comment by davidiw** [comment]
https://github.com/libra/libra/blob/master/secure/net/src/lib.rs#L260 or https://github.com/libra/libra/blob/master/consensus/safety-rules/src/safety_rules.rs#L150

**Comment by davidiw** [comment]
maybe this is a trivial tweak in kibana?

**Comment by davidiw** [comment]
cc: @sherry-x thoughts?

**Comment by sherry-x** [comment]
Yeah I've been having this issue as well, lots of logs does not have "message" field and if you try to just show message field it's empty. but I also agree setting message field is just duplication. we can probably do different filter for different module so that the output message is useful, example: https://85bd0f3d76314c71869bce3ae260f6d2.us-west1.gcp.cloud.es.io:9243/goto/3f58e3783a9f4bd352591287df1b9281

**Comment by davidiw** [comment]
That doesn't really work well, @sherry-x, usually I'm not debugging a specific component but I'm debugging an issue and jumping across multiple components. @bmwill / @gregnazario, we really need to have a default string otherwise it makes kibana a pain to use. If there isn't an easy fix to duplicate the data upstream, I propose we just bite the bullet for now and duplicate the data in our code.

**Comment by gregnazario** [comment]
I'm fine with duplicating the data, but we've got to be careful that the data isn't too large

**Comment by sherry-x** [comment]
Yeah it's not great to have missing message when debugging general issues. As long as it's not tons of data we can add it for now (Association is paying it anyway ¯\_(ツ)_/¯)

**Comment by bmwill** [comment]
Given we've had issues with throughput of logs before I'm hesitant to just duplicate the data. Also just dumping the data in as a JSON string into an empty message field seems not very readable. A default string would probably bring more harm than good since then we'll end up with a ton of similar messages making debugging a bit harder.

**Comment by davidiw** [comment]
Okay, maybe we can make this an attribute on my schema?

**Comment by gregnazario** [comment]
> Okay, maybe we can make this an attribute on my schema?

Something like this?
```
#[derive(Schema)]
#[schema(data_to_message)]
pub struct Schema {
    ...
}
```

**Comment by bmwill** [comment]
Something like that wouldn't be ideal for usability reasons. What happens if you also include a message? If this is something that we want to do, it should be handled on the backend, just before sending the data out. I'm fine with duplicating the data I was just hoping since this is really a "kibana" issue that we could fix it in kibana and not in libra

**Comment by bmwill** [comment]
Give me a second and I'll have a PR whipped up

**Comment by gregnazario** [comment]
> Something like that wouldn't be ideal for usability reasons. What happens if you also include a message? If this is something that we want to do, it should be handled on the backend, just before sending the data out. I'm fine with duplicating the data I was just hoping since this is really a "kibana" issue that we could fix it in kibana and not in libra

This actually brings up the bigger point of how do we handle duplicated data fields in schemas and non-schemas?  Which one wins?

Kibana is a pretty simple client and just prints out directly what's in the database.  There might be some complicated way to do it, but tbh I'm not an expert in doing anything too fancy with it, and it tends to slow down pretty quickly when you do too much complicated things.

**Comment by bmwill** [comment]
It's dependent on the implementation of how the Logger collects the key/value pairs. Currently we do "last one wins" if there happen to be two key's that match.

**Comment by davidiw** [comment]
Thanks everyone for having a thorough conversation on this, identifying an acceptable though not ideal solution, and @bmwill for getting it done!
