### ISSUE TITLE
[Bug] submit should return transaction expired error if the transaction is expired

### ISSUE THREAD

**Issue by xli** [libra/libra#6321]
# 🐛 Bug

## To reproduce

Example signed transaction hex: 1668F6BE25668C1A17CD8CAF6B8D2F2502000000000000000160A11CEB0B0100000006010002030206040802050A0707111A082B100000000100010101000201060C000109000C4C696272614163636F756E740C6164645F63757272656E63790000000000000000000000000000000101010001030B0038000201070000000000000000000000000000000105436F696E3105436F696E31000010270000000000000100000000000000034C425200CA9A3B00000000020020F549A91FB9989883FB4D38B463308F3EA82074FB39EA74DAE61F62E11BF55D254086A0D142FE8397A2C27888F007C4A920E28A1411CCDE9D7E9E2A01CAAFAD0271A8EE56F82F5940FC7A556434E5CDEAB776E8B00FBA9F9721642D9A97E25F0A07

The transaction expiration timestamp is set to 1000000000  (2001-09-08 18:46:40 -0700)
Submit success.
The transaction is not executed and drop some where unknown.

## Expected Behavior

Submit should return MempoolStatusCode::VmError error code
MempoolStatusCode has VmError: transaction didn't pass vm_validation
and vm validation has: TRANSACTION_EXPIRED

**Comment by xli** [comment]
The reported transaction seq number > account seq number. We won't be able to do vm validation before seq number is current.

Maybe mempool should do expiration validation ?

**Comment by christinacelee** [comment]
mempool does run all VM validation for txns with seq number > account seq number, but it seems the VM validation itself only returns the TRANSACTION_EXPIRED error for seq number = account seq number (committed on chain) + 1. @runtian-zhou is this intentional?

**Comment by runtian-zhou** [comment]
This is actually as expected... The reason is that the vm-validation will run the full function prologue and do an error conversion. Since the expiration time check happens after the sequence number check in the prologue, error in sequence number will surpress the txn expiration check. The sequence too new error was then transformed into n OK signal, having the expiration check to not run in the vm-validation. This might not be a big issue tho as the full prologue will be run in the execution phase again, thus even if the txn expires it will eventually get rejected in the execution phase. 

The fix to this issue should be easy: to move the line of expiration check to be before the sequence number too new check (and also make sure no other checks are run after the sequence number too new). Do we want to commit a fix like this? cc @sblackshear @dariorussi

**Comment by christinacelee** [comment]
I think if the fix is small we should push to get this in - if there's a txn we know will get rejected from execution (in consensus), might as well reject it ASAP, i.e. at JSON-RPC/mempool submission 😄
