### ISSUE TITLE
Does Libra use Solidity ? I wanted to create a small payments system which can convert crypto assets into digital currency and also cash. How do we write smart contracts in Libra ?

### ISSUE THREAD

**Issue by lopeselio** [libra/libra#6624]
### Please note that this issue tracker is not a help form and this issue will be closed.

Please contact the development team on [Discourse](https://community.libra.org)

**Comment by bob-wilson** [comment]
Libra uses the Move programming language for transaction scripts and smart contracts, not Solidity. We have some preliminary documentation available now:

https://developers.libra.org/docs/move-overview
https://developers.libra.org/docs/run-move-locally

More detailed documentation will be available in the future.

Note: Instead of filing GitHub issues to ask questions like this, I suggest you post on the Libra community forums instead:
https://community.libra.org/

**Comment by lopeselio** [comment]
Thanks @bob-wilson  did not know about the community forum.
