### ISSUE TITLE
[Feature Request] Shuffle the (n-1) last addresses of each peer

### ISSUE THREAD

**Issue by huitseeker** [libra/libra#759]
# 🚀 Feature Request

Since
https://github.com/libra/libra/commit/5e2d74a88466c01fbad4a53dfbf9610f1dfefce7
we dial the alternate addresses of peers in round-robin fashion.

We could be shuffling the (n-1) last elements of addrs. It does not entail other changes, can be done [easily](https://docs.rs/rand/0.7.0/rand/seq/trait.SliceRandom.html#tymethod.shuffle) and:
-  makes the dial behavior less predictable (so there's less incentive to knock off a node because your controlled host is next on the list), 
- serves as a poor man's load balancer,

It seems like it's a straightforward improvement, because the intended meaning from the configuration is often "here's the guy I want you to dial, but you can try any of the others if it doesn't work"

**Comment by bothra90** [comment]
@huitseeker, @phlip9 : I'm not sure I agree that we need to shuffle at all. The addrs that we chose to connect in a round-robin fashion all belong to a single node (validator/full node). So do we really need to worry about predictability in dial order or load balancing?

**Comment by phlip9** [comment]
Hmm, I guess the load balancing story doesn't really check out, since it's the same validator node behind the endpoints. The predictability also seems unnecessary since the ordering is independent between different validators; an attacker controlling one validator cannot affect the ordering of our dials to another validator. Likewise, an attacker controlling one addr in the list of a validator's listen addrs still has to pass authentication checks when we dial them.

**Comment by huitseeker** [comment]
The load balancing, as for the control issues, is of course between network links, not validators.
