### ISSUE TITLE
Are the coins minted in testnet valuable?

### ISSUE THREAD

**Issue by fxsjy** [libra/libra#91]

**Comment by bioharz** [comment]
Short answer: I don't think so.

Long answer:
Well, let's define value. More specific, let's have a look intro supply and demand.
In an ordinary blockchain project like BTC or ETH, every testnet party can mint testnet coins. They are even many websites, to get free testnet coins.
And for developers, there is a real demand. But since they can mint the testnet coins pretty easy or get free coins on sites like [coinfaucet.eu](https://coinfaucet.eu/en/btc-testnet/) or [faucet.ropsten.be](https://faucet.ropsten.be/), they don't pay real money for testnet coin.
In the case of libra, I don't know yet more specific details about the testnet.

**Comment by TechniumUnlimited** [comment]
About as valuable as the ones that will be on mainnet (not valuable)

**Comment by fxsjy** [comment]
@TechniumUnlimited , mainnet coin also has no value? Are you serious? :-)

**Comment by bioharz** [comment]
Very toxic environment at the moment on GitHub Libra issues. I don't see any objective arguments against Libra.
Many negative emotions from the crypto space. I really can't understand those emotions.

**Comment by Solexplorer** [comment]
@bioharz Crypto has always been like that

**Comment by bitcoinheiro** [comment]
This project is under scrutiny from all sides. It should be positive if it can survive all the scrutiny. Money triggers adversarial environment

**Comment by TechniumUnlimited** [comment]
@bioharz Centralized, Permissioned, Censorship-Inducing, Shitcoins Will Never Have a Valid Place in the "Crypto Space" - and you can see clearly why, not only is it terrible for the average person, the government steps in immediately when there are single or few centralized points of control/attack, such as with this project. France, EU, and US Governments want total control over this and it's only been announced for 1 day.

**Comment by marczeller** [comment]
back to the question :
Libra testnet coins can be easily and without any kind of limitation minted out of thin air by anybody running the CLI client.
Based on that, I don't see how they can have any "market value".

**Comment by kphfb** [comment]
Testnet coins are simply for testing purposes.  You are free to mint as many as needed for testing.  They have no real-world value and in fact the balances will be periodically reset during testnet as we made changes/improvements to the system.

**Comment by antonio-fr** [comment]
"mint" command is a query to a faucet server. It is not actually "minted".
