### ISSUE TITLE
[Bug] Build Error in Ubuntu 18

### ISSUE THREAD

**Issue by AnilChinchawale** [libra/libra#92]
# 🐛 Bug

## To reproduce
./scripts/cli/start_cli_testnet.sh

** Code snippet to reproduce **
```rust
~/github/facebook/libra$ ./scripts/cli/start_cli_testnet.sh
Building and running client in debug mode.
   Compiling grpcio-sys v0.4.4
   Compiling ring v0.14.6
   Compiling url v1.7.2
   Compiling slog-async v2.3.0
   Compiling unicase v2.4.0
   Compiling unicase v1.4.2
error: failed to run custom build command for `grpcio-sys v0.4.4`

```

** Stack trace/error message **
```
error: failed to run custom build command for `grpcio-sys v0.4.4`
```

**Comment by Kixunil** [comment]
#83 fixed it for me.

**Comment by c-edw** [comment]
Could you run it with `RUST_BACKTRACE=1`? It should look like `RUST_BACKTRACE=1 ./scripts/cli/start_cli_testnet.sh`. Then paste the full output here.

**Comment by wqfish** [comment]
Hi @AnilChinchawale can you provide full error message with more information?

**Comment by icarter09** [comment]
@AnilChinchawale  I've been going over the all the logged issues and noticed several times that user's are having problems with Ubuntu 18.04. Here are some of the issues: #19, #30, #94, #79. Look them over and see if any of them contain the solution to your current problem.

Also please let me know if one of those fixed the issue as I'm looking to create a section on the README that contains helpful guidance for Ubuntu installs (since this keeps showing up). Thanks.
